### PR TITLE
Cleanup developer doc

### PR DESCRIPTION
**Pull request by jsakkine**
Clean up the developer guide a bit so that adding new documentation does not make it a bigger mess (e.g. remarks about ARM and BuildRoot).

### CODE REVIEW

**Comment by jsakkine** [comment]
"Screenshot":

https://github.com/jsakkine/surge/blob/cleanup-developer-doc/doc/Developer%20Guide.md

**Comment by baconpaul** [comment]
Still says closed: not closes:
The git section refers to the commit message section below but it it is now above
Otherwise lgtm

**Comment by jsakkine** [comment]
I guess the whole sentence about commit messages is next to useless.

**Comment by jsakkine** [comment]
Updated.

**Comment by baconpaul** [comment]
Lgtm merging

**Pull request merged**
