### PR TITLE
Manage VST3 menu references properly

### LINKED ISSUE #1952: Bitwig functions crash VST3
**Describe the bug**
Bitwig has additional options for Surge's VST3 instrument:

- Map to Controller or Key
- Add Automation Lane
- Set to Default Value

These options do not exist for the VST2.

When any of the following options is selected Surge will crash

offset

auto

* Surge Version: commit 24f7676
* Plugin type: VST3
* Bits: 64
 - OS: Linux Debian Buster 10.3
 - Host: Bitwig 
 - Version: 3.2 beta 7

### PR DESCRIPTION
**Pull request by baconpaul**
Bitwig Linux hands us a menu where it doesn't keep a count
which is fine, but it means we have to to avoid a VST3 menu
crash.

Closes #1952. The menus no longer crash

### CODE REVIEW

**Comment by tank-trax** [comment]
still crashes when selecting

- Map to Controller or Key
- Add Automation Lane
- Set to Default Value

**Comment by baconpaul** [comment]
I literally did all of those in 3.2 beta 7 and it crashed without my change and didn't crash with. 100% sure you rebuilt?

**Comment by tank-trax** [comment]
commit 64507f75

Screenshot_20200527_111828

**Comment by baconpaul** [comment]
And the fix is in aba980. You are one behind.

**Comment by tank-trax** [comment]
odd, I did another git pull am up to date now, will test and report back in a bit

**Comment by tank-trax** [comment]
it no longer crashes using commit aba980 
however - Set to Default Value does not reset the value
not sure if the functions are working

**Comment by baconpaul** [comment]
Yeah OK cool so no crash but no work. I wonder if I have to retain something else also. Thanks

**Comment by tank-trax** [comment]
Tested and all functions work properly

- Map to Controller or Key/Clear Controller Assignment
- Add Automation Lane/Delete Automation
- Set to Default Value

**Pull request merged**
