### PR TITLE
"New Vocal Wavetables for Surge" by Layzer

### PR DESCRIPTION
**Pull request by esaruoho**
https://www.kvraudio.com/forum/viewtopic.php?p=7313640#p7313640

when asked about if he would allow it to be added to surge:
```
sure, no problem. i put it out there for everyone.
i just dont want people selling them.
```

### CODE REVIEW

**Comment by baconpaul** [comment]
“Xlz Voc” is not a great name for the parent directory for users - can we use a better name somehow?

**Comment by esaruoho** [comment]
@baconpaul agreed. i'll consult layzer

**Comment by baconpaul** [comment]
Cool. And maybe code up a 3rd party wt file also so we get a line like in patches. All to do to do

**Comment by esaruoho** [comment]
referenced at #603

**Comment by esaruoho** [comment]
@baconpaul while there's a to-do-to-do on that 3rd party wt file format / separator, could this be merged anyway? :)

**Comment by baconpaul** [comment]
I'd rather get to the separator. I promise I will.

**Comment by esaruoho** [comment]
@baconpaul ok cool! :)

**Comment by baconpaul** [comment]
OK @esaruoho I'm going to close this PR and pull your commit onto my branch `baconpaul/third-party-wavetables-603` where I implement the separator. I'll sweep these wavetables in along with the separator code. (I'll leave you in the commit log don't worry!)

This also means I can delete this branch hanging around in the surge repo, so I'll do that too.

**Pull request closed without merging**
