### PR TITLE
Initial version of build-linux.sh

### PR DESCRIPTION
**Pull request by jsakkine**
Add a similar build script as build-macosx.sh. Copies plugin DLL's and
configuration.xml to local directories. Does not yet copy presets and
wavetables, but it is a starting point.

Signed-off-by: Jarkko Sakkinen <jarkko.sakkinen@iki.fi>

### CODE REVIEW

**Comment by jsakkine** [comment]
First PR for #360. Will need a 2nd one for presets and wavetables.

**Comment by baconpaul** [comment]
Looks familiar! Chuckle

Will merge

I will also fnish the widows powershell version shortly mostly works now

**Comment by jsakkine** [comment]
Yeah, there might be some similarities to build-osx.sh :)

**Comment by baconpaul** [comment]
Anyway I just pushed the rough equivalent for windows

```
scripts\win\build-win.ps1
```

you run it in powershell and it will do everything you need without needing to start visual studio. You probably need to do a visual studio build once to do the nuget (I should add that) and it's not as good as the osx and lin versions but good enough that I use it now.

**Pull request merged**
