### PR TITLE
Add support of various file dialog options on Zenity

### PR DESCRIPTION
**Pull request by jpcima**
This adds better zenity file dialog support. #1102

This is supported:
- initial directory
- selecting directories
- file filters

Also, there is a quoting routine for passing safe arguments to popen.

### CODE REVIEW

**Comment by baconpaul** [comment]
Looks fantastic; thanks.

I would say the entire zenity implementation is something I did quickly because it was becoming untenable to have nothing. Happy for any other changes, corrections, or thoughts you have.

Will merge now.

**Comment by baconpaul** [comment]
Also: It's wonderful to have another dev working on this stuff. Really glad for the efforts!

**Comment by jpcima** [comment]
I noted 2 other defects, related:

- it invokes the callback even without selection. If the user clicks cancel, Linux user interations are invoking it with empty string.
One could imagine it may be interesting to act in response to a "cancel" click.
However it doesn't seem how Surge works: when you ask to open a tuning, and cancel, it will warn that it's not a valid SCL file.

- About SCL: open an invalid file, or non existing. If the tuning variable "count" is equal to 0, it attemps a divide by it, and raises FPE which crashes.

**Comment by baconpaul** [comment]
On behaviors: The mac is really the definitive example. Since that's the one I use almost all the time. If you look at UserInteractiosnMac.mm you can see it only calls the callback if you click OK. Clearly linux should do the same.

On the second: non-existing gets fixed by above. Invalid is much harder. There's no great way to detect if an sci file is valid. But an FPE crash is dumb - we should clearly be more defensive in the parser. That's all in src/common/Tunings.cpp if you want to look!

**Pull request merged**
