### PR TITLE
Fix clang-format check in pipeline builds

### PR DESCRIPTION
**Pull request by mvf**
The clang-format check was doing nothing in clean working copies (e.g.
pipeline builds) because it was diffing against HEAD.

This change makes it always check all cached .cpp and .h files in the
relevant directories. Delta checks via "git diff --name-only" require
deep clones (>330 MB and growing) and would likely be slower on Azure.
Checking everything takes <3 seconds on my machine.

@baconpaul I won't just merge this until you've had a chance to look at it. Especially `src/common/ModulationSource.h`, where I had to manually expand comments without fully knowing what they mean. :sweat_smile:

#3204

### CODE REVIEW

**Comment by baconpaul** [comment]
Ha well I was surprised at how well we were doing with prs but I have been running git clang format before commits 

anyway looks like it failed in the pipeline with an error - do you have access to the pipeline logs?

**Comment by mvf** [comment]
Yes, `clang-format` is not installed on the macOS VM. Any particular reason to run this on macOS? Otherwise I'd move it to a Linux job.

**Comment by baconpaul** [comment]
How did it work before then?

but no it could run in Linux too

**Comment by baconpaul** [comment]
Oh right it ran before because it sent no args into xargs in the pipeline! Doh

thanks for fixing all of this. Appreciated!!

**Comment by mvf** [comment]
OK, let's try this with Linux then. `clang-format` was never called on the macOS VM because `git diff` produces no output when there are no unstaged changes.

**Pull request merged**
