### PR TITLE
Migrate message boxes to new UI

### LINKED ISSUE #5663: Make juce::AlertWindow look like our miniedits
So that styling and `dialog` skin colors are all picked up the same way.

This means they should have a titlebar just like miniedits and overlays do, the whole nine yards with Surge icon in top left etc. What is currently the headline of AlertWindow should be printed centered in the titlebar.

### PR DESCRIPTION
**Pull request by tejas1993**
Closes #5663.

Previous: 
Current message box

New: 
message box new

Question: Unless I'm missing something, exactly one message box remains: https://github.com/surge-synthesizer/surge/blob/21baada63f332f62b32df3ac2c794b3250e221b8/src/surge-fx/SurgeFXEditor.cpp#L598 
Since it's in surge-fx, I'll have to link the surge-xt project in the surge-fx makefile to use the work we've done so far? That seems like overkill for this, is there something I'm missing?

### CODE REVIEW

**Comment by mkruselj** [comment]
We can leave the surge-fx thing alone, since that has quite a different GUI. So this basically means the issue on Surge synth side is done and dusted! 🙂

**Comment by tejas1993** [comment]
Yup! [This issue](https://github.com/surge-synthesizer/surge/issues/5663) can close once this is merged

**Comment by tejas1993** [comment]
Sooooo.... some errors say we can't have forward references to enums, and windows build is refusing to accept that Alert exists if we just include the header file. Hmmm, puzzling. 

I will try to fix/work around.

**Comment by tejas1993** [comment]
There yah go.

**Pull request merged**
