### PR TITLE
Adding four new sine oscillator waveforms

### PR DESCRIPTION
**Pull request by K0rrid0r**
Some additional sinusoidal based waveforms

### CODE REVIEW

**Comment by mkruselj** [comment]
You need to install clang-format extension for Visual Studio and run it on modified files (open each file then Ctrl+R, Ctrl+D) then push that commit.

**Comment by baconpaul** [comment]
as well as clang format I have some questions about the code

1. why are you comparing wfmode with values in the branches where it is set? does that do anything?
2. some of the logic seems super wonky

if (quadrant == 2 || quadrant == -1)
         {
             pvalue = sin2x;
             if (quadrant == 3 || quadrant == 2)
                 pvalue = 0;
         }
         break;

This is just "if quandrant==2 || quadrant == 3 pvalue=0" right?


and value 27 seems to just bine sine2x/quadrant. but there's lots of other code.

So not quite sure what you are trying to do with those branches?

**Comment by baconpaul** [comment]
Screen Shot 2021-02-28 at 11 57 57 AM

Like: This is a mistake right? That's your wave 25 as coded. Not quite sure what you want there.

Can you share screenshots of what you are trying to do?

**Comment by baconpaul** [comment]
Anyway look at `baconpaul/korr-four` which cleans up your code and does what I think you wanted the code to do. Lemme know.

**Comment by K0rrid0r** [comment]
> Screen Shot 2021-02-28 at 11 57 57 AM
> 
> Like: This is a mistake right? That's your wave 25 as coded. Not quite sure what you want there.
> 
> Can you share screenshots of what you are trying to do?

That's exactly what i was trying to do. I thought it was interesting. So this is me also trying to understand the code. Some stuff makes sense and some not.

Anyway i would accept *baconpaul/korr-four* as a fix to this ofc.

**Comment by baconpaul** [comment]
> > Screen Shot 2021-02-28 at 11 57 57 AM
> > Like: This is a mistake right? That's your wave 25 as coded. Not quite sure what you want there.
> > Can you share screenshots of what you are trying to do?
> 
> That's exactly what i was trying to do. I thought it was interesting. So this is me also trying to understand the code. Some stuff makes sense and some not.
> 
> I was listening very closely to every new waveform and compared sounds and timbre so i did not end up in something that already existed. That waveform that is on display will make interesting sounds in FM just because of the square in it.
> 
> Anyway i would accept _baconpaul/korr-four_ as a fix to this ofc.

Yeah the problem with generating a square that way is it is super-aliased basically and will sound badly across the higher audio spectrum. It's not the appropriate way to do that.

But I'll close this and merge kore-four

**Comment by K0rrid0r** [comment]
> > > Screen Shot 2021-02-28 at 11 57 57 AM
> > > Like: This is a mistake right? That's your wave 25 as coded. Not quite sure what you want there.
> > > Can you share screenshots of what you are trying to do?
> > 
> > 
> > That's exactly what i was trying to do. I thought it was interesting. So this is me also trying to understand the code. Some stuff makes sense and some not.
> > I was listening very closely to every new waveform and compared sounds and timbre so i did not end up in something that already existed. That waveform that is on display will make interesting sounds in FM just because of the square in it.
> > Anyway i would accept _baconpaul/korr-four_ as a fix to this ofc.
> 
> Yeah the problem with generating a square that way is it is super-aliased basically and will sound badly across the higher audio spectrum. It's not the appropriate way to do that.
> 
> But I'll close this and merge kore-four

You mean in higher samplerate maybe?

**Comment by baconpaul** [comment]
Higher frequency.

**Comment by K0rrid0r** [comment]
> Higher frequency.

Yeah ok! sorry for the confusion but i do hear what you mean now (just listening to it in very high freq) that's something i need to test next time i add something like this. Thanks for the lesson.

**Comment by baconpaul** [comment]
No problem.
Low alias high frequency square waves is why the modern oscillator is lots of math and calculation and not just `(phase > 0.5) ? -1 : 1`

**Pull request closed without merging**
