### PR TITLE
Move Function from Coming in 1.9 to Coming soon

### PR DESCRIPTION
**Pull request by baconpaul**
So many things might change
We might call it surge 2 or surge 2021.2
We might want to do a 1.9 release before function is done
We might never do a 1.9 release (but then soon would also be a lie :) )
So hedge a bit on this UI point

### CODE REVIEW

**Comment by mkruselj** [comment]
"Coming in a future version" would probably be the most correct, I suppose.

**Comment by baconpaul** [comment]
32 chars

**Comment by mkruselj** [comment]
Coming TBD?

Half a year isn't something I'd call "soon"?

**Comment by baconpaul** [comment]
How about just "coming..."

**Comment by mkruselj** [comment]
How about: `Function (work in progess!)`, 27 chars.

**Comment by baconpaul** [comment]
Sold! Let me push that now.

**Pull request merged**
