### PR TITLE
Prevent modulation smoothers from running away to infinity

### LINKED ISSUE #6835: Reliable Crash, 1.1.2, Windows, Reaper latest
From William Fields

[crash-example.zip](https://github.com/surge-synthesizer/surge/files/10609352/crash-example.zip)

this minimal reaper project crashes at measure 4 when played with XT 1.1.2

baconpaul confirmed on his win 11 box.

### PR DESCRIPTION
**Pull request by mkruselj**
Closes #6835

### CODE REVIEW

**Comment by baconpaul** [comment]
Oh isinf can be kinda expensive I think I was thinking we would fix this by clamping chanfe not isinf outout

**Comment by mkruselj** [comment]
Oh we could clamp for sure what should be the clamping range?

**Comment by baconpaul** [comment]
The thing to clamp is b. My fix was something like if b blows out jump to target iirc

**Comment by baconpaul** [comment]
But I didn’t out that in the issue sigh sorry

**Comment by mkruselj** [comment]
Right but what would be the range to test b against? What is considered as "b blew up"?

**Comment by baconpaul** [comment]
20? That’s why the issue is still open o want to run it in a few cases and see what’s reasonable and what’s crazy

**Pull request merged**
