### PR TITLE
Revert "Skip VST3 Menus in Reason"

### PR DESCRIPTION
**Pull request by mkruselj**
Reverts surge-synthesizer/surge#6766

Test to see if Reason Studios actually fixed it. Surely they wouldn't lie to us!

### CODE REVIEW

**Comment by baconpaul** [comment]
I am not sure if the fix is out of beta yet. They gave me beta access to file a bug. So this may be premature

**Comment by mkruselj** [comment]
This is just for @esselfortium to test in latest beta. Pretty sure that beta will be out before 1.3, probably.

**Comment by mkruselj** [comment]
Aaaaaaaand confirmed working. In the current stable version, not beta! So it's out already and we're good.

image

**Comment by mkruselj** [comment]
Confirmed fixed on latest Reason _stable_ release. So it's out of beta and we're good!

image

**Comment by baconpaul** [comment]
Oh awesome!!
and thanks to reason folks if they read this for giving me beta access to confirm and report :)

**Pull request merged**
