### PR TITLE
Osc work

### PR DESCRIPTION
**Pull request by pkstone**
- OSC out IP address is settable
- OSC out for Parameters give true float values
- /q/all_mods implemented
- many small improvements

### CODE REVIEW

**Comment by baconpaul** [comment]
Looks great to me. Is this ready to merge? If so lets merge it!

**Comment by mkruselj** [comment]
I would suggest not squashing this time around, perhaps?

**Comment by baconpaul** [comment]
Makes sense - that means I can't do it for my phone though! :) 

I'll rebase merge this later today unless someone screams

**Comment by baconpaul** [comment]
I decided to squash it. Too many intermediate commits and I didn't want to rebase it into 3 since that requires terminal and git-fu and you can't do it from GitHub web. But it's all merged!

**Pull request merged**
