### PR TITLE
Allow custom juce path for surge-rack builds

### PR DESCRIPTION
**Pull request by falkTX**
This is needed in order to use a custom JUCE for surge-rack, as the JUCE dirs are hardcoded to the local files.

### CODE REVIEW

**Comment by baconpaul** [comment]
Thanks!

**Comment by baconpaul** [comment]
Oh I presume another PR is inbound which sets this variable in the rack build right?

**Comment by baconpaul** [comment]
(the reason this is here is because SURGE_JUCE_PATH is set as CURRENT_SOURCE_DIR which is wrong in rack; if you don't have a fix to that also let me know and I'll correct this diff)

**Comment by baconpaul** [comment]
oh actually we don't need to change anything in rack if we fix one more thing in surge cmake. 

```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 7740ffe9..173ca278 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -9,7 +9,7 @@ if (NOT SURGE_COMPILE_BLOCK_SIZE)
   set(SURGE_COMPILE_BLOCK_SIZE 32)
 endif()
 
-set(SURGE_JUCE_PATH "${CMAKE_SOURCE_DIR}/libs/JUCE" CACHE STRING "Path to JUCE library source tree")
+set(SURGE_JUCE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../libs/JUCE" CACHE STRING "Path to JUCE library source tree")
 
 list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
 include(cmake/lib.cmake)
```

that's the extra diff we need then rack builds with this change too.

**Comment by baconpaul** [comment]
i'll commit that now

**Comment by falkTX** [comment]
I dont have the fix for the surge-rack side at this point, so your initiative is quite welcome (ensuring no breakage)
Thanks for the quick merge!

**Comment by baconpaul** [comment]
no problem. with my change in #6844 surge rack builds fine. (And that's actually how I should have done it in the first place!)

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge-rack/pull/835 pulls it into surge-rack also

**Comment by baconpaul** [comment]
oh if you are doing a cardinal surge upgrade also I'll probably do a 2.1.2 next week with extended envelope times in one module, just FYI. Tuesday maybe or weds it will be ready? Won't be any substantial code change from head though.

**Comment by falkTX** [comment]
I hope to have a 23.02 cardinal release, but no defined date for that yet besides "sometime later this month".
I already updated to latest suge 2.1.1 in preparation for the new plugins, builds fine now mostly just dealing with this juce related things

**Comment by baconpaul** [comment]
Great well I merged the change with the adjustable juce path to head so should be good 

did you get cmake build workinf or did you write an alternative makefile out of curiosity? If the later I would be happy to check in a makefile.cardinal if that’s easier for you l

**Comment by falkTX** [comment]
there is a big makefile to deal with building all plugin files for all the modules. I do not use the rack-style of makefile import for building plugins.
surge stuff defined in https://github.com/DISTRHO/Cardinal/blob/main/plugins/Makefile#L1032

**Comment by baconpaul** [comment]
Oh gotcha. The. Our move to cmake didn’t impact you. That’s good

**Pull request merged**
