### PR TITLE
Implement sampleRateReset() method for Tape effect

### LINKED ISSUE #6834: Tape kills audio when oversampled
Load a Surge in Reaper
Oversample it to 196k 
Latch or something
Load the tape FX
Sound dissappears.

### PR DESCRIPTION
**Pull request by mkruselj**
@Andreya-Autumn Please test! :)

### CODE REVIEW

**Comment by Andreya-Autumn** [comment]
Building to test now.

**Comment by mkruselj** [comment]
Darn it! Well ok then it seems it may be a Mac only issue, since I'm not getting it on Win here?

**Comment by baconpaul** [comment]
Should we merge this change anyway?

**Comment by mkruselj** [comment]
I haven't had the chance to test if this changes the sound vs previous version at different SRs... can we have a confirmation on this before the merge? I will be honest and say I'm not feeling particularly inspired to conduct that research 😅

**Comment by baconpaul** [comment]
I just read the code. We should merge it even if it is not the full fix. its a definite improvement

**Pull request merged**
