### PR TITLE
Two Zoom Changes (Resolution and Extrema)

### LINKED ISSUE #540: 125% is more pixelated than 100%, and more pixelated than 150%
from KVR 
https://www.kvraudio.com/forum/viewtopic.php?p=7308336#p730833 6

```
maybe I'm wrong - that zooming to 125% blurs the GUI
(more than 100%), while to 150% makes it crispy sharp
again. Is there some merit to this observation, or I 
just have to consult an optician?
```

from kvr 
https://www.kvraudio.com/forum/viewtopic.php?p=7308336#p7308336

### LINKED ISSUE #590: Zoom to biggest
@esaruoho made a comment on slack like “I zoom to 150 then jog up by 10s to the biggest I can get”. 

We have the function to find the biggest. Maybe just bind it to a menu item “zoom to biggest” which does that in one step

### PR DESCRIPTION
**Pull request by baconpaul**
Activate the 125x assets by making them callable in CScalableBitmap,
activating them in win script, and re-rendering the win resource files.

Also add a function "Zoom to Largest" which takes zoom to exactly the
point below where we would warn that you can't zoom any larger for your
screen.

Closes #540: Activate 125% assets
Closes #590: Zoom to Biggest Menu

### CODE REVIEW

**Comment by baconpaul** [comment]
This is all pretty mechanical. @jsakkine or @kzantow if you want to peek appreciate it. I'll probably sweep tomorrow evening eastern unless I hear otherwise. Thanks!

**Comment by esaruoho** [comment]
tested with vst2/renoise and au/logic. 125% looks great. renoise handles max res nice.

but logic OTOH:
image

**Comment by baconpaul** [comment]
Ahh that's because the window decoration trim is too aggressive. I need to turn it back. Sigh.

**Comment by baconpaul** [comment]
Pushed a change to max it out at 90% on mac as well as win.

**Pull request merged**
