### PR TITLE
Complete AU Preset layer exposed

### LINKED ISSUE #405: AU Preset Names
currently, for instance, Logic or Live do not show the "currently selected surge preset name" in the daw.

### PR DESCRIPTION
**Pull request by baconpaul**
Onlky factory presets
Better naming
Correct ordering
Closes #405

### CODE REVIEW

**Comment by mkruselj** [comment]
Don't you think it should also contain 3rd party presets, since this is also considered a part of Factory?

**Comment by baconpaul** [comment]
So I chose to do factory only because this is the Logic UI

Screen Shot 2020-06-23 at 8 47 42 AM

And this is the surge UI

Screen Shot 2020-06-23 at 8 47 49 AM

If you choose a preset outside of factory it correctly renames the logic track though, which is the desired behavior.

**Comment by mkruselj** [comment]
Gotcha.

This is why I'd like to see 3rd party presets just merged into the factory. I mean they are installed in the factory data folder and everything, yet are treated specially... eh - preset browser will sort that out, someday...

**Comment by baconpaul** [comment]
yeah indeed.

**Pull request merged**
