### PR TITLE
Capitalize global constants

### PR DESCRIPTION
**Pull request by jsakkine**
I might need to add couple of new constants to globals.h as part of my Linux work (namely WINDOW_SIZE_X and WINDOW_SIZE_Y), and I don't want to add anything new with a wrong convention. Generally I think that a good point of time to do coding style fixes is when you need to otherwise change the associated code. I know it is a large diff but the change is fairly mechanical search and replace.

We could later on namespace these (lets say Surge::Globals) but I think that can be later on a separate commit. Right now for me the priority is to be able to add new global constants in capital letters :)

I did test VST2/VST3/AU builds and also tried out VST2 and AU plug-ins in Ableton.

### CODE REVIEW

**Comment by baconpaul** [comment]
I've run out of time to look at this tonight, I'm sorry. I will try and make some time Thursday unless @kurasu gets a chance.

It looks like the right thing to do to me, but it also looks like the kind of thing that one typo could compile and break us, so I want to have time and focus to check it carefully.

Thanks!

**Comment by baconpaul** [comment]
OK I had a minute and realized reading these diffs is not going to work.

So I diffed vs master into a file called 'x' and then ran this

```
prev = []
next = []
with(open("X")) as f:
    for line in f:
        if(line.startswith("-")):
            prev.append(line)
        elif(line.startswith("+")):
            next.append(line)
        else:
            if(len(prev) > 0):
                for pair in zip(prev, next):
                    previ = pair[0][2:]  # strip off the " +"
                    nexti = pair[1][2:]

                    if(previ.lower() != nexti.lower()):
                        print("DIFF\n", pair[0], pair[1])

                prev = []
                next = []
```

and it showed that there were no problems. I also did a test build mac and it all worked.

Just need to to a test build windows and I'll merge this. Have to run an errand now so may not be until morning.

**Comment by baconpaul** [comment]
Ahh nope it doesn't build on windows.

src/common/SampleLoadRiffWave gives me an error

```
(p3env) paul:~/dev/music/surge$ grep -r block_size src/
src//todo/sub3_osc_dot.cpp:	for(k=0; k<block_size_os; k++)
src//todo/sub3_osc_sample.cpp:	for(int k=0; k<block_size_os; k++)
src//todo/sub3_osc_wavetable2.cpp:	float block_pos = oscstate[voice] * block_size_os_inv * pitchmult_inv;
src//todo/sub3_osc_wavetable2.cpp:		for(int s=0; s<block_size_os; s++)
src//todo/sub3_osc_wavetable2.cpp:		float a = (float)block_size_os*pitchmult;
src//todo/sub3_osc_wavetable2.cpp:	float hpfblock alignas(16)[block_size_os];
src//todo/sub3_osc_wavetable2.cpp:	li_hpf.store_block(hpfblock,block_size_os_quad);		
src//todo/sub3_osc_wavetable2.cpp:	for(k=0; k<block_size_os; k++)
src//todo/sub3_osc_wavetable2.cpp:	vt_dsp::clear_block(&oscbuffer[bufpos],block_size_os_quad);	
src//todo/sub3_osc_wavetable2.cpp:	bufpos = (bufpos+block_size_os)&(ob_length-1);		
src//todo/effect_emphasize.cpp:	float bL alignas(16)[block_size << 1];
src//todo/effect_emphasize.cpp:	float bR alignas(16)[block_size << 1];
src//todo/effect_emphasize.cpp:	pre.process_block_U2((__m128*)bL,(__m128*)bR,(__m128*)bL,(__m128*)bR,block_size_os);	
src//todo/effect_emphasize.cpp:	for(int k=0; k<block_size_os_quad; k++)
src//todo/effect_emphasize.cpp:	post.process_block_D2((__m128*)bL,(__m128*)bR,block_size_os);		
src//todo/effect_emphasize.cpp:	outgain.MAC_2_blocks_to((__m128*)bL,(__m128*)bR,(__m128*)dataL,(__m128*)dataR,block_size_quad);
src//common/SampleLoadRiffWave.cpp:   unsigned int samplesizewithmargin = WaveDataSamples + 2 * FIRipol_N + block_size + FIRoffset;
src//common/vt_dsp/halfratefilter.cpp:const unsigned int hr_block_size = 256;
src//common/vt_dsp/halfratefilter.cpp:   __m128 o[hr_block_size];
src//common/vt_dsp/halfratefilter.cpp:   __m128 o[hr_block_size];
src//common/vt_dsp/halfratefilter.cpp:   __m128 o[hr_block_size];
src//common/vt_dsp/lipol.cpp:   lipol_block_size = _mm_cvt_si2ss(m128_zero, bs);
src//common/vt_dsp/lipol.cpp:   m128_bs4_inv = _mm_div_ss(m128_four, lipol_block_size);
src//common/vt_dsp/halfratefilter.h:   // unsigned int block_size;
src//common/vt_dsp/lipol.h:   __m128 lipol_block_size;
src//common/dsp/BiquadFilterSSE2.cpp:	for(int k=0; k<block_size; k+=2)
src//common/dsp/BiquadFilterSSE2.cpp:	for(int k=0; k<block_size; k+=4)
src//common/dsp/BiquadFilterSSE2.cpp:	for(int k=0; k<block_size; k+=4)
src//common/dsp/BiquadFilterSSE2.cpp:	for(int k=0; k<block_size; k+=4)
src//common/dsp/BiquadFilterSSE2.cpp:	for(int k=0; k<block_size; k+=4)
src//common/dsp/WavetableOscillator.cpp:      FMfilter.process_block(&master_osc[block_size]);*/
```

So can't merge sorry!

**Comment by baconpaul** [comment]
screen shot 2019-01-15 at 6 20 20 pm

**Comment by jsakkine** [comment]
@baconpaul, thank you for the review! I have now Windows environment. I'll fix the issues and test this with OpenMPT.

**Comment by jsakkine** [comment]
Still working on getting my Windows environment functional. Any tips how to get pixel size doubled in VirtualBox. Everything looks so small on MacBook Pro Retina display.

**Comment by jsakkine** [comment]
Maybe this will work https://superuser.com/questions/1253860/virtualbox-macos-host-windows-10-guest-retina-resolution

**Comment by baconpaul** [comment]
there's a scale menu in view but you have to install the VirtualBox in vm extensions first

but i switched away from VirtualBox a few days ago after being generally underwhelmed with performance

**Comment by baconpaul** [comment]
I spent the money on parallels 14 and am way happier. Try a demo before you buy

**Comment by jsakkine** [comment]
@baconpaul, this probably categorizes as home/personal use?

**Comment by baconpaul** [comment]
Yeah I think so. You mean the 79 vs 99 bucks?

**Comment by baconpaul** [comment]
I was about to say "this still breaks" when I realized you haven't pushed!

```
diff --git a/src/common/SampleLoadRiffWave.cpp b/src/common/SampleLoadRiffWave.cpp
index 98f176c..865dcf9 100644
--- a/src/common/SampleLoadRiffWave.cpp
+++ b/src/common/SampleLoadRiffWave.cpp
@@ -216,7 +216,7 @@ bool Sample::load_riff_wave_mk2(const char* fname)
    //  this->sample_start = 0;
    this->channels = (unsigned char)waveFormat.Format.nChannels;

-   unsigned int samplesizewithmargin = WaveDataSamples + 2 * FIRipol_N + block_size + FIRoffset;
+   unsigned int samplesizewithmargin = WaveDataSamples + 2 * FIRipol_N + BLOCK_SIZE + FIRoffset;^M
    sample_data = new float[samplesizewithmargin];
    unsigned int i;
    for (i = 0; i < samplesizewithmargin; i++)
```

here's the diff you need. 

After UserInteractions I'd love to get this in since I'm moving that code around for #198, so if you have time for one thing today, the UserINteractions is still most important to me, but if you have time for two, that diff would be next.

Thanks!

**Comment by jsakkine** [comment]
@baconpaul, thanks I'll prioritize user interactions and this tomorrow. Lets try to get both merged then.

**Comment by jsakkine** [comment]
@baconpaul, realized too obvious and easy way to do tree-wide search replaces:

```
git grep -l block_size_os | xargs sed -i 's/block_size_os/BLOCK_SIZE_OS/g'
```

I'll take a time to write a  shell script now that does this completely mechanically (takes only few minutes) and redo the whole commit.

**Comment by baconpaul** [comment]
Make sure to do it in the right order if you do that. Block-size-osx before block-size-os and so on

**Comment by jsakkine** [comment]
@baconpaul, absolutely :) i can paste the shell script here you get both the script and the code change :)

**Comment by jsakkine** [comment]
```
#!/bin/bash

tokens=(
block_size_os_quad
block_size_os_inv
osc_oversampling
block_size_quad
ob_length_quad
block_size_inv
block_size_os
max_fb_comb
max_unison
block_size
namechars
ob_length)

for token in ${tokens[*]}
do
	token_up=$(echo $token|tr 'a-z' 'A-Z')
	echo "$token -> $token_up"
	git grep -l "$token" | xargs sed -i "s/$token/$token_up/g"
done
```

**Comment by jsakkine** [comment]
OK, here is the script and change made by that script.

**Comment by baconpaul** [comment]
Great and reverse engineer checking it with my script also shows you got it. Just wrapping up my windows build and then I'll merge this one too!

**Pull request merged**
