### PR TITLE
 fix #544 Inactive buttons [Linux] 

### LINKED ISSUE #544: Linux: Inactive buttons
the KEYTRACK and RETRIGGER buttons in the Oscillator section do not change colours, either to yellow or back to black, if clicked in Linux

they do appear to be active though

same for the red M and S buttons in the Scene section
the green Filter buttons just below however are functional

### PR DESCRIPTION
**Pull request by rghvdberg**

### CODE REVIEW

**Comment by baconpaul** [comment]
Cool. But this or has more commits than just the fix. Maybe best to close it and submit from a branch with just your change and not the other 4 commits?

**Comment by esaruoho** [comment]
@baconpaul loox like he fixed it.

**Comment by baconpaul** [comment]
Yup! Don’t suppose you can test on Mac that mute and solo still work with this branch could you? If not I can do so later tonight or tomorrow

**Comment by baconpaul** [comment]
Confirms this works on mac.

**Comment by baconpaul** [comment]
And confirms it works on windows. Will update commit comment and merge.

**Pull request merged**
