### PR TITLE
Fix for 125x misalignment #612

### PR DESCRIPTION
**Pull request by itsmedavep**
My math was off somehow. That is fixed up now and source file is updated.

Apologies! 

#612

### CODE REVIEW

**Comment by baconpaul** [comment]
screen shot 2019-02-15 at 4 22 06 pm

here's windows 125x with these assets

1. The FX box is cropped at the bottom
2. There's white lines at the top of the envelope
3. The menu button bottom border isn't rendered

I think they are still a bit wonky

If you want to try this on mac and have a build and compile you want to do these thigns

1. edit CScalableBitmap and comment back in the 3 places I commented out 125
2. edit src/mac/DisplayInfoMac and make getDisplayBackingScale return 1.0 no matter what

then when you zoom to 125% you will get a 125 asset even on an HDPI display.

**Comment by itsmedavep** [comment]
Sigh. 

Do the assets look OK at other sizes. Its an entirely new set of background images. For all scale sizes. 

I ask because I didn't see anything wrong when I built and checked on a retina and non retina display. I really am trying to check this stuff to the best of my abilities before checking in.  

Regardless, Ill try to get a look at what you suggest above and see if I can figure out what is happening.

**Comment by itsmedavep** [comment]
Just quickly trying to verify some things since Im not on a machine to build with yet.

The original 1x size is this:
904px by 542px

125% of that is:

1130px by 677.5px <- I cant render to subpixels! 

Curious if the 125% files are the correct dimensions.

**Comment by itsmedavep** [comment]
Notes from slack:

https://surgesynth.slack.com/archives/CF7C7V2PM/p1550274694041400

https://surgesynth.slack.com/archives/CF7C7V2PM/p1550278426047600

https://surgesynth.slack.com/archives/CF7C7V2PM/p1550278618050100

**Comment by baconpaul** [comment]
@itsmedavep I'm going to close this one dave, since "the special secret project" may help it in another way.

**Pull request closed without merging**
