### PR TITLE
Rename Combinator modes to mystery box

### PR DESCRIPTION
**Pull request by mkruselj**
Also a break; was missing so Bonsai routing options were bleeding through the RM volume parameter's context menu

### CODE REVIEW

**Comment by baconpaul** [comment]
Still would be lovely if this was a data structure in a header in src common rather than embedded in the gui! Then I could use the same names in rack

**Comment by mkruselj** [comment]
> Still would be lovely if this was a data structure in a header in src common rather than embedded in the gui! Then I could use the same names in rack

Can do that. SurgeStorage.h, then?

**Comment by baconpaul** [comment]
> > Still would be lovely if this was a data structure in a header in src common rather than embedded in the gui! Then I could use the same names in rack
> 
> Can do that. SurgeStorage.h, then?

I would put it right after the enum for ring mod modes, yeah. And probably add an `n_ringModModes` to the end of the enum also. (Sorry we discussed this on discord but i didn't write it in an issue)

**Comment by baconpaul** [comment]
Awesome looks good to me! Thank you

**Pull request merged**
