### PR TITLE
Wavetable and User Data Improvements

### LINKED ISSUE #288: ~/Documents/Surge could have a wavetables folder for user-generated wavetables?
Since presets are saved to `~/Documents/Surge/subfolders` - it would only make sense to have the wavetables be saved into the same place (like subfolders of `~/Documents/Surge/wavetables` maybe?

Otherwise the user needs to go to `~/Library/Application Support/Surge/wavetables` and copy them there. not very user-friendly

### LINKED ISSUE #488: Surge Menu could have a button that opens the user folder on OS file browser
as suggested by `EvilDragon` at https://surgesynth.slack.com/archives/CF6NVE4RW/p1549216822192300 - 

It would be really useful to give the user a button in the Menu that opens the user documents folder of Surge, and another for factory folder (in case wavetables have not been integrated into `~/Documents/Surge` by the time that button starts existing.

### LINKED ISSUE #603: divider between library-wavetables and 3rdparty-wavetables
"And maybe code up a 3rd party wt file also so we get a line like in patches. All to do to do" as uttered by @baconpaul

### PR DESCRIPTION
**Pull request by baconpaul**
This diff implements a collection of improvements for how you
open, access, and navigate user data and third party data, especially
wavetables. It adds the following features

1. Allows .wt files to exist in ~/Documents/Surge and appear in the
   wavetable directory

2. Allows .wt files to exist in (surge-data-folder)/wavetables_3rdparty

3. Gives a function to open both the factory and user data folder in your
   OS appropriate file explorer

4. Adds subdirectory and heirarchy support to wavetables

5. Adds the "New Vocal Wavetables for Surge" pack from Layzer as discussed
   https://www.kvraudio.com/forum/viewtopic.php?p=7313640#p7313640

This diff addresses several issues

Closes #603 : Separator to 3rd party wavetables
Closes #288 : .wt files from ~/Documents/Surge
Closes #488 : Open a user folder and factory folder from menu

### CODE REVIEW

**Comment by baconpaul** [comment]
@esaruoho I would love it if you could find some time to test this out to see if it does what you want. (and it only does .wt; still no .wav)

**Comment by esaruoho** [comment]
first feedback:

in ~/Documents/Surge, I have a wavetables -folder with subfolders VFXTW which has subfolders VFX-OS and VFX-TW. These are not visible here:
image

now i have moved them from ~/Documents/Surge/wavetables/VFXTW/VFX-TW to wavetables/VFX-TW just to see what might happen.

image


So, sub-sub-folders are not yet accepted, but otherwise, they load. so, this is great! can ya add sub-subfolder support? otherwise this is good to go. Tested with VST2Renoise/Logic/AU,Live/VST2.

**Comment by esaruoho** [comment]
anyway, lgtm! sub-sub-subfolders can be tweaked in later.

**Comment by baconpaul** [comment]
Huh sub sub folders should work; that’s a bug. I’ll give it a test and see if I can find it!

**Comment by baconpaul** [comment]
Thanks for testing!

**Comment by esaruoho** [comment]
@baconpaul sub-sub-folders work.. sub-sub-sub-folders don't :)

**Comment by baconpaul** [comment]
Yeah got it. But that’s a sign of a wierd bug. i didn’t assume depth anywhere. So would like to try and figure it out!

**Comment by baconpaul** [comment]
Oh hold on - another bug. I broke the "window" wavetable with this change. Won't merge until I fix it.

**Comment by baconpaul** [comment]
Oh no that was just a bad build. We're all good!

**Pull request merged**
