### PR TITLE
wavetable morph adjust

### PR DESCRIPTION
**Pull request by blancoberg**
* Removed the "morph" interpolation method as you could clearly hear when it was switching over on higher frequency modulations. Now it only uses the new continuous mode.

* Changed the way the new continuous mode reacts to the "extend range" flip. Before it would just remove the interpolation between each in between frame in a block, which made almost no difference in the overall sound. So now it instead removes the inbetween frames entirely, basically switching directly from the "last frame" to "current frame" which is probably closer to how the legacy method works. 

* Fixed a minor mistake in the switch implementation which affected the attack and the waveform display.

### CODE REVIEW

**Comment by mkruselj** [comment]
I wonder if we can make the new quantized mode (continuous mode disabled) work like the PPG did? Meaning, it would only switch to a new wavetable frame after the current single cycle has finished, instead of immediately.

**Comment by blancoberg** [comment]
> I wonder if we can make the new quantized mode (continuous mode disabled) work like the PPG did? Meaning, it would only switch to a new wavetable frame after the current single cycle has finished, instead of immediately. This would be a very nice improvement IMO.

it could work, but you would have to store a separate morph value for each voice in that case, otherwise they would all switch simultaneously on different phases. I guess the reason for switching at the ends is for reducing noise right? it does require all the frames to start and end at the same value otherwise it wouldn't work that great

**Comment by blancoberg** [comment]
this would be super useful for me personally IF we could also have a mode for the pitch slider where that is also only allowed to change when a cycle is finished.

With those two, it would be possible to build super smooth legato transitions. Easier said that done though, as I'm pretty sure switching pitch in the middle of a block will screw everything up

**Comment by mkruselj** [comment]
> I guess the reason for switching at the ends is for reducing noise right?

Yes, because PPG did not do any sort of interpolation between frames.

**Comment by baconpaul** [comment]
folks i'm a bit behind. where are we on this. Do we want to merge it or are there outstanding changes?
Thanks!

**Comment by baconpaul** [comment]
(Just want to make sure you aren't waiting on me! If you are waiting on other things that's fine!)

**Comment by blancoberg** [comment]
I think you can merge. I'm not really sure about that "wait until cycle is finished" bit, as that will defeat the purpose of all the other changes I'v made to make the timing better between pitch & morph.

either way its a big fix so that will have to be in a separate pr

**Pull request merged**
