### PR TITLE
Allocate SurgeVoice with the new-operator

### PR DESCRIPTION
**Pull request by jsakkine**
By using alignas() and adding an empty default constructor, we can
preallocate SurgeVoice instances in the same way we would allocate them
with _aligned_malloc().

Signed-off-by: Jarkko Sakkinen <jarkko.sakkinen@iki.fi>

### CODE REVIEW

**Comment by baconpaul** [comment]
The code looks OK and builds; could you just outline how you tested it? Like did it make sound mac and windows both? Thanks for all this modernization. Super important!

**Comment by baconpaul** [comment]
Oooh no this isn't my env. This diff stops the plugin from loading bitwig 2 windows 10 vst2.

If I build master I have no problem. If I build your diff rebased to that same master I don't load in bitwig 2 VST2 windows 10. 

I don't think this is mergeable right now from my perspective.

**Comment by jsakkine** [comment]
Looking into that.

**Comment by jsakkine** [comment]
- Ableton 10 macOS: VST2 and AU works.
- Bitwig: I get the same error.

Really interesting side-effect. Cannot see the relation between plug-in metadata and SurgeVoice. And odd that it still works in Ableton. I'll try out Windows to see what is the outcome there.

**Comment by jsakkine** [comment]
VST2 works also on Windows.

**Comment by jsakkine** [comment]
I get the same result. With this change Bitwig Studio does not load the plugin. Without it does.

**Comment by jsakkine** [comment]
I did a test where I changed the existing constructor as reset-function in order to test if the compiler gets confused. Did not help, still pushed the change as a separate commit as it anyway makes sense.

@kurasu, do you see anything that could cause the problem?

**Comment by jsakkine** [comment]
BTW, would make sense to only free osc's when freeing voice (looking at SurgeSynthesizer implementation). Now the re-use thing for voices is kind of half done, but lets fix this issue first.

**Comment by baconpaul** [comment]
Yeah well I'm glad you also see it! I also have no idea what's in that code path. Like I said, host <> plugin interactions are ... varied. Who knows what is being checked by bitwig!

but bitwig must be trying to load the dll. Wonder if a few good fprintf( log file ... ) type things in the startup path could show you what it is calling.

**Comment by jsakkine** [comment]
Did not see it before because only today I installed Bitwig.

**Comment by baconpaul** [comment]
Yeah it's luck that I use that as my windows host. What windows hosts do you use for testing?

**Comment by jsakkine** [comment]
I have Windows 10 Pro running on VMWare Fusion on my MacBook Pro at the moment that has OpenMPT installed. I think I'll also install Bitwig Studio Demo there so that I can VST3 also on Windows.

**Comment by baconpaul** [comment]
OK cool. I have win10 home with bitwig. I will grab openmpt next time I'm looking at windows.

I should finish my PowerShell script so it installs the VST3 for me as well as the VST2. That will make my life much easier. Just a few run-as and I'm done.

**Comment by jsakkine** [comment]
Really weird. In the latest version I have explicit create() and destroy() functions, to make sure that the code is absolutely in the C++ standard constraints but still the same result. And loads with other hosts.

**Comment by baconpaul** [comment]
Huh I wonder what it is doing?

**Comment by jsakkine** [comment]
Still a mystery. Would make more sense if the plugin would fail on all hosts.

**Comment by kurasu** [comment]
oh, look like i messed up with git here.. it was only supposed to include 
301169f & 620a544

**Comment by baconpaul** [comment]
Np. You ok to rebase and cherry pick or should I?

**Comment by kurasu** [comment]
Maybe the git doesn't like that i rebased my copy of the branch towards master before i pushed it to jsakkine's branch?

**Comment by kurasu** [comment]
you can feel free to do it, git is not my native tounge

**Comment by baconpaul** [comment]
Yeah looks like it. I think if we also rebase @jsakkine branch then it’s all ok. I’ll take a look after dinner (unless @jsakkine is online and looking)

**Comment by baconpaul** [comment]
Sorry probably won’t get to unpicking this tonight. Will do so when I next get a bit of dev time tomorrow or weds unless @jsakkine beats me to it

Thanks for the diffs and fixes. Appreciated!

**Comment by jsakkine** [comment]
Quite overloaded with kernel stuff for a while, but I'll be back :)

**Comment by baconpaul** [comment]
thanks! Will leave this one to you!

**Comment by jsakkine** [comment]
Great! I'll soon start to look at Linux side again (mainly building and packaging). Thank you for merging this.

**Comment by jsakkine** [comment]
@baconpaul, @kurasu, was there some progress on Bitwig issue, or why this needed to be rebased? Have been badly following the project for  a week period.

**Comment by kurasu** [comment]
@jsakkine This commit should fix the issue with in bitwig studio.

**Comment by jsakkine** [comment]
@kurasu, Thank you.
OK, so I included now @kurasu's commits and now when I try to compile this branch, I get:
```
$ ./build-osx.sh --build-validate-au

Building surge-au with output in build_logs/build_au.log
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/jjs/devel/surge/obj/x64/Release/surge-au/surge-au.build/Objects-normal/x86_64/aulayer_cocoaui.o /Users/jjs/devel/surge/src/au/aulayer_cocoaui.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

** Build of au failed**
src/common/gui/SurgeGUIEditor.h:11:9: error: no type named 'PluginGUIEditor' in namespace 'VSTGUI'; did you mean simply 'PluginGUIEditor'?
src/common/gui/SurgeGUIEditor.h:32:31: error: base specifier must name a class
:17: error: 
21: error: no member named 'getRect' in 'SurgeGUIEditor'

Complete information is in build_logs/build_au.log
```

**Comment by baconpaul** [comment]
That looks an awful lot like you are not merged with master

In master, SurgeGUIEditor.h line 11 has "VSTGUI::PlugGuiEditor" as the EditorType which I changed in commit eb31ce45 when I was fixing the vst3sdk upgrade. Without the namespace you will get an error like that.

**Comment by jsakkine** [comment]
These are on top of latest master. I cherry picked the commits.

**Comment by baconpaul** [comment]
Well does SurgeGUIEditor.h have that namespace in it? The error is consistent with it not. What's the top 20 lines of that file?

**Comment by jsakkine** [comment]
Yes.

**Comment by jsakkine** [comment]
Cannot be other than latest master because `git fetch mainline && git reset --hard mainline/master` and then cherry picked stuff.

**Comment by jsakkine** [comment]
```
//-------------------------------------------------------------------------------------------------------
//	Copyright 2005 Claes Johanson & Vember Audio
//-------------------------------------------------------------------------------------------------------
#pragma once

#include "globals.h"

#if TARGET_AUDIOUNIT
//#include "vstkeycode.h"
#include <vstgui/plugin-bindings/plugguieditor.h>
typedef VSTGUI::PluginGUIEditor EditorType;
#elif TARGET_VST3
#include "public.sdk/source/vst/vstguieditor.h"
typedef Steinberg::Vst::VSTGUIEditor EditorType;
#elif TARGET_VST2
#include <vstgui/plugin-bindings/aeffguieditor.h>
typedef VSTGUI::AEffGUIEditor EditorType;
#else
#include <vstgui/plugin-bindings/plugguieditor.h>
typedef VSTGUI::PluginGUIEditor EditorType;
#endif
```

**Comment by baconpaul** [comment]
And you updated your submodule also?

That message had to get fixed in the vst3sdk so either the code and modules mismatch or my upgrade was wrong somehow or your repo is wrong somehow. I don’t think your repo or my upgrade are it. So maybe submodule update init recursive then a clean all?

**Comment by jsakkine** [comment]
I removed the whole vst3sdk directory before the update...

**Comment by baconpaul** [comment]
Ok. Let me pull your branch when I’m home later today and see what happens. 

Away from computer a chunk of the day.

**Comment by baconpaul** [comment]
Your branch here the one you force pushed is the one that broke?

**Comment by jsakkine** [comment]
Yeah, I cherry picked commit's from @kurasu's tree and force pushed.

**Comment by jsakkine** [comment]
Not sure what you mean when you say "your branch". Does Github change the associated branch somehow in the middle or? Github is relatively alien platform to me (where as Git isn't).

**Comment by baconpaul** [comment]
OK the problem is that the reset --hard doesn't update submodules.

```
paul:~/dev/music/surge$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
paul:~/dev/music/surge$ git fetch jsakkine
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 18 (delta 13), reused 15 (delta 13), pack-reused 2
Unpacking objects: 100% (18/18), done.
From https://github.com/jsakkine/surge
 + ac88970...7147cd0 allocate-surgevoice-using-new -> jsakkine/allocate-surgevoice-using-new  (forced update)
   e674f12..a34e8b4  master                        -> jsakkine/master
paul:~/dev/music/surge$ git checkout jsakkine/allocate-surgevoice-using-new
M	vst3sdk
Note: checking out 'jsakkine/allocate-surgevoice-using-new'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 7147cd0 Cleaned up memory management
paul:~/dev/music/surge$ git status vst3sdk/
HEAD detached at jsakkine/allocate-surgevoice-using-new
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   vst3sdk (new commits)

no changes added to commit (use "git add" and/or "git commit -a")
paul:~/dev/music/surge$ git checkout master vst3sdk/
paul:~/dev/music/surge$ git status
HEAD detached at jsakkine/allocate-surgevoice-using-new
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   vst3sdk
```

so you need to pull the vst3sdk pointer from master explicitly. Don't know why this didn't happen with your pull.

Once you've done that, you can git submodule update --init --recursive and you should see this

paul:~/dev/music/surge$ (cd vst3sdk; git log) | head -1
commit 82380a8faa33824123104e005bcffb0451151d88

with that done you can push the submodule pointer back to your branch and it will build.

It is a bit upsetting that git reset --hard reset surge but not the submodules. But a checkout or merge would do it. That feels like a git bug to me but I'm not a super expert. I just know your branch doesn't have the pointer moved and the above commands will get you building.

Best!

**Comment by jsakkine** [comment]
Hey, why do checks fail? Looks like for all active PRs.

**Comment by jsakkine** [comment]
Can confirm that works on Windows too (the same DAW).

**Comment by jsakkine** [comment]
I guess this is ready for merge.

**Comment by baconpaul** [comment]
Yay! Merging!

**Comment by jsakkine** [comment]
Wow, finally!

**Pull request merged**
