### PR TITLE
Implement a settings menu

### PR DESCRIPTION
**Pull request by baconpaul**
We used to have the 'about' button but that only does one thing
As we want to do more ot the synth, we want options, and that's
a great place to hang them. So change it to 'menu' and make it pop
up a menu with a couple of options.

I'd appreciate someone reviewing and/or testing this. @esaruoho or
@jsakkine maybe?

And remember this is 'path to zoom'. In the near future there will be a zoom
submenu here which sets size. (And I'll probably implement user defaults
to remember your preference too)

Thanks!

### CODE REVIEW

**Comment by baconpaul** [comment]
Oh and the issue describing this is #342

**Comment by baconpaul** [comment]
Oh one quick force coming in. I left a debug on!

**Comment by baconpaul** [comment]
screen shot 2019-01-19 at 10 59 38 am

There you go! That's the new look.

**Comment by esaruoho** [comment]
Confirmed on LogicProX/AU

fullscreen_19_01_2019__19_51

Confirmed on Renoise/VST
fullscreen_19_01_2019__19_52

**Comment by baconpaul** [comment]
Thanks! I'm going to merge this one so I can proceed to step 2 on the 'path to zoom' sometime later today. Which is to do a zoom menu!

**Comment by jsakkine** [comment]
Looks good, can be refined if need.

**Pull request merged**
