### PR TITLE
doc: Update the commit message format

### PR DESCRIPTION
**Pull request by jsakkine**

### CODE REVIEW

**Comment by jsakkine** [comment]
Probably does also with the format I documented because Github recognized "Closes:"

**Comment by baconpaul** [comment]
Your doc says closed: rather than closes:; if that works too all good with me! Changes look great

Recently I’ve used 

Closes #xya: blah blah
Closes #sdd: Blum boom

And that’s closed issues for me and looked good

**Comment by jsakkine** [comment]
Oops, should have said `Closes: <issue>`. That was just a typo. I'll update this commit soonish.

**Comment by baconpaul** [comment]
Cool. Merge away once once fixed thanks!

**Pull request merged**
