### PR TITLE
Add a waveform display to the oscilloscope

### PR DESCRIPTION
**Pull request by mx**
Some limitations:

* It doesn't let you change parameters yet.
* Doesn't normalize the input data in case the gain is way up.
* Honestly, it just scrolls super fast since you view 100 ms at a time. I'm not sure how useful that is, really. I don't use waveform scope displays.

### CODE REVIEW

**Comment by mx** [comment]
Also I haven't profiled this yet. At this point I just want to get the checkpoint into nightlies so people can try it and suggest any changes.

**Comment by planist79** [comment]
Hi, i asked for an oscilloscope (waveform view) a few days ago on Discord, and Paul told me there was something in the making. When i read on Discord it is now implemented in the nightly i had to install it and i found the new oscillator in the options menu. 

Great! Thank you for this.
Regarding the waveform view. 
1. It reacts to sound quite slow, there is a latency of ~1 second between hearing the sound and its display in the waveform view window.
2. Also, it would be great if one could choose how many zero-crossings of the waveform is displayed. (so to see a simple saw wave i would choose 2 zero crossings. Maybe you can have a look at "Melda Oscilloscope" or "s(m)exoscope".. 
 
Thank you again!

**Comment by mx** [comment]
@planist79 
Yeah, the latency of 1 second is unfortunately there to prevent missing any information. I can probably lower it to like...half a second. Making it instantaneous could be challenging though to ensure that the update rate stays exactly even.

Of course, if you just want to use a zero-crossing mode like you suggested, then none of that matters.

Is the idea with the zero-crossing thing that the scope stops once you get two, until you manually start it again? I don't actually use a waveform oscilloscope, so I don't even know what features people usually want with them. I only wanted the spectrum analyzer, haha.

**Comment by mx** [comment]
Other people's PRs for functionality here are welcome btw. Like I said, I've never used a waveform scope before.

**Comment by mx** [comment]
Also looks like S(m)exoscope is GPL, perhaps we're better off just importing and adapting it for the waveform display.

**Comment by planist79** [comment]
You are right, waveform view is not necessarily helpful for the technical analysis of the sound you are creating - but as a visual feedback it is helpful... 

A soft synth is able to give much more visual feedback on the parameters and parameter changes (modulation, etc) than hardware synths can, just because of the big display. and this is one major advantage. 

Ideas:
1. implement the oscilloscope as "Effect" which can be placed somewhere in the fx signal chain 
2. an option to place the waveform/frequency spectrum window  permanently in the bottom right corner of the GUI (below the fx section).. IMO it would make the main GUI much more dynamic and visually pleasing.

**Comment by mx** [comment]
@planist79 take a look at the latest nightly, I merged the s(m)exoscope code into the waveform view. It should behave identically.

**Comment by planist79** [comment]
> @planist79 take a look at the latest nightly, I merged the s(m)exoscope code into the waveform view. It should behave identically.

Great, thank you. i get the nightly and get back to you.

**Comment by planist79** [comment]
thank you. It works well! 
Some side notes
- there's still a noticeable latency, could it be lowered?00 
- could the window be resizeable?
- zero crossing option works quite well, even when changing the waveform the visualization is quite stable.

when I play around a bit more I come back to you...Thank you!!

**Comment by mx** [comment]
> there's still a noticeable latency, could it be lowered?

There shouldn't be any latency at all. Do you have "sync" turned on? If so, turn it off.

> could the window be resizeable?

It's a tear-out window, so tear it out and resize.

**Comment by planist79** [comment]
1. ok,
2. ok, thank you.

**Pull request merged**
