### PR TITLE
Pybind: Add ability to process inputs

### PR DESCRIPTION
**Pull request by dhatadi**
Added extra function called processMultiBlockWithInput on Python side which takes two arrays, one for input and one for output. This copies data to the SurgeSynthesizer input array before processing. Note that the input and output arrays must match in size, type, and dimensions.

### CODE REVIEW

**Comment by baconpaul** [comment]
This looks great and I'm happy to merge it

We do a clang-format check on all our C++ in our CI pipeline. If you can clang-format your code and re-push I'll merge, but if you are on an env without clang-format I can also do it in the morning.

Thanks for contributing this!!

**Comment by dhatadi** [comment]
Sorry about missing the clang-format check. I did read that in the docs and usually use it but forgot to this time! I'll sort it out shortly.

**Comment by baconpaul** [comment]
Great. Can you add yourself to the AUTHORS file when you do also?

Really appreciate you jumping in to add this. Thanks!!

**Comment by baconpaul** [comment]
Great thanks, merged and I think this also closes #7672 which is cool.

If you are on our discord or join, please do make sure to identify yourself to us and we will give you the team/contributor role!

And thanks again

**Comment by dhatadi** [comment]
And thank you!

**Pull request merged**
