### PR TITLE
Headless linux

### PR DESCRIPTION
**Pull request by jsakkine**
Necessary changes to build-linux.sh in order to test headless version with ARM.

### CODE REVIEW

**Comment by baconpaul** [comment]
Any reason you removed clean-all? I use that quite often to make sure I'm back to a no-built-asset state. I'd prefer it stays if that's OK?

Also can you squash your commits?

And why does this PR have changes to vstgui.surge? Need that fixed before we sweep. Are you sure your submodule is up to date with master?

Thanks!

**Comment by jsakkine** [comment]
@baconpaul, not sure which should be squashed. They are logically distinct changes. That is the granularity I usually apply. Clean commit can be dropped.

**Comment by baconpaul** [comment]
Well, definitely the commits which commit a changed vstgui.surge need addressing right! Can't merge with that there.

I've been squashing into a single over-commit recently and find it makes me write a nice summary of the overall change (after you asked me to squash commits on a PR about 6 weeks ago :) ). I'm fine to have multiple commits though.

**Comment by jsakkine** [comment]
IMHO the right size for commit is when it does something functional, is fairly self-contained and leaves the tree in a consistent state. It makes the review easier too. I'll update this soonish.

**Comment by jsakkine** [comment]
OK, updated and rebased.

**Comment by jsakkine** [comment]
I can create a BuildRoot recipe after this has been merged.

**Comment by baconpaul** [comment]
LGTM. Feel free to merge! Thanks.

**Pull request merged**
