### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by adiastra**
Remove IRC

### CODE REVIEW

**Comment by trebmuh** [comment]
Why removing it?

**Comment by esaruoho** [comment]
@adiastra let's not have personal preference dictate what should be in the surge readme.md or not.

we had a ton of Linux users on the surge IRC channel helping with the Linux implementation. Let's not just randomly remove IRC "just because"...?

**Comment by baconpaul** [comment]
Yeah @adiastra was missing a bit of historical context; and also the channel has been dead for a while. We chatted about it some on slack and I’m not going to merge the change. The irc channel is still alive and Bridged to slack

**Comment by trebmuh** [comment]
Maybe it's dead because everything runs smoothly so far... for now.
Just as a bit of contextual, it's not because I'm not talking in there right now that I'll never ever do it again. I'm working on other stuff right now. And the LV2 version seems to work quite well. But if I found something strange or if I've got a Feature Request to do, I'll probably use the IRC channel to talk about it.

**Comment by baconpaul** [comment]
That’s exCtky what I explained on slack

**Comment by trebmuh** [comment]
:sunglasses: then

**Pull request closed without merging**
