### PR TITLE
Headless can write wav files

### PR DESCRIPTION
**Pull request by baconpaul**
To debug click n pop I want headless to be able to make a file
I can hear. This change allows that by (1) making CMakeLists
check for libsndfile and (2) if it is there building a libsndfile
writer

### CODE REVIEW

**Comment by baconpaul** [comment]
@jsakkine hey. When debugging click-n-pop I realized I wanted headless to be able to write wav files. The change to debug click and pop is bigger than this one (including making headless no longer assume 44.1k as it does here). But along the way I had to figure out how to create a .wav

So this change adds the (incredibly small) libsndfile code to write a wav file. But it also does the cmake shenanigans to get libsndfile if it is installed and not if it isn't. I tested this by building on mac where i had libsndfile, then on linux where I didn't, then installing libsndfile and building again. It all worked as expected.

The packages are

```
brew install libsndfile
```

on mac and

```
sudo apt-get install libsndfile1-dev
```

on ubuntu

I am *not* going to sweep this for the beta7 tomorrow. But wanted to put it here for (1) you to review and (2) if you think it is good to go for you to merge.

I can get on with my debugging without this in master so no rush.

**Comment by baconpaul** [comment]
Oh also I didn't use `find_package` because libsndfile has (apparently) an experimental CMake build only so I used the find_library / find_path combo.

**Comment by baconpaul** [comment]
Actually I am going to force push this so sample rate is an argument. Hold on before you review.

**Comment by baconpaul** [comment]
OK @jsakkine I just pushed a version which does exactly this. You are right - it is cleaner. Makes me think about how to factor the CMakeFile generally... but have to make headless work windows before we think about bigger things.

Anyway I'm not going to merge this before beta 7 tomorrow morning. But if you want to merge it while I'm away or fix it up and merge it, that would be super. I am sure it will help folks working on headless and c-n-p problems.

Cool stuff!

**Comment by jsakkine** [comment]
Yeah, now it looks great!

**Comment by baconpaul** [comment]
OK I'm going to merge it then, now that beta 7 is out!

**Pull request merged**
