### PR TITLE
Move multi switches to XML

### PR DESCRIPTION
**Pull request by apalm**
This PR addresses https://github.com/surge-synthesizer/surge/issues/1316.

It moves the following to XML:

* waveshaper type
* filter envelope mode
* amp envelope mode
* LFO shape
* LFO trigger mode

Screen Shot 2019-12-01 at 10 35 19

One issue is that the `Filter EG` section doesn't show the envelope mode multi switch; I'm not sure why.

Since https://github.com/surge-synthesizer/surge/issues/1316 states "once the sliders are moved", I also moved a few more sliders:

* waveshaper drive
* filter balance

However, if you prefer that the slider moves aren't part of this PR, I can back them out.

### CODE REVIEW

**Comment by baconpaul** [comment]
Wow thank you! And welcome to surge! You may want to also join our slack by the way. We end up chatting about the tool quite a lot over there. But GitHub is great too.

Let me take a few minutes and do a quick review and also see if I can figure out why the filter env isn’t showing up. From your code changes it looks like they should so will pull it into my copy and run it.

Oh and you probably also want to add yourself to the AUTHORS file if you want to push that into your branch.

**Comment by baconpaul** [comment]
OK here's why it didn't show the filter and why it didn't work.

You called your 'LFOs trigger' thing 'filters.env.mode' 

```
diff --git a/resources/data/layouts/original.layout/layout.xml b/resources/data/layouts/original.layout/layout.xml
index 1ab9f68..1f5e50d 100644
--- a/resources/data/layouts/original.layout/layout.xml
+++ b/resources/data/layouts/original.layout/layout.xml
@@ -688,7 +688,7 @@
 
       </layout>
       <layout height="auto" width="auto" style="roundedlabel" bgcolor="$mod.bg" fgcolor="$mod.fg" label="Modulator">
-        <node component="60x12 Multi" guiid="filter.env.mode" xoff="170" yoff="20" width="60" height="36">
+        <node component="60x12 Multi" guiid="lfo.trigmode" xoff="170" yoff="20" width="60" height="36">
           <nodeproperties rows="3" cols="1" choices="$freerun|$keytrigger|$random"/>
         </node>
         <node component="60x18 Switch" xoff="170" yoff="65" guiid="lfo.unipolar">
```

this diff makes it work.

I found this as follows

1. I ran it with stdout attached
2. On stdout I saw the error

```
ERR :  Failed to construct component 'lfo.trigmode' with failmsg 'No Component for guiid '
```

3. I then realized you hadn't laid it out in the layout but it was there so went and looked
4. et voila

We should really make it so that if you have two nodes with the same guild we pop a clearer error.  I meant to do that when I added readonly nodes last week but didn't.

Let me do a quick review of the rest of it now, but if you want to also push up the fix to the XML I think we will be in good shape.

**Comment by baconpaul** [comment]
Yup, just did a quick once over and other than that layout issue above, it's all good.

If you do another push fixing the XML I will squash and merge.

Welcome to team surge synth!!

**Comment by apalm** [comment]
Oops 🤦‍♂️. I pushed the change. Thanks for digging in, the detailed explanation, and the welcome :)

**Comment by baconpaul** [comment]
Great, I merged it in. Super stuff! You just took my Monday Morning dev list and cleared it :)

**Pull request merged**
