### PR TITLE
Fixed typo on line 33

### PR DESCRIPTION
**Pull request by kant**
* on line 78: we develop against `master` and arne takes diffs against `develop`:  what does it mean `arne`?

### CODE REVIEW

**Comment by baconpaul** [comment]
arne is the name of the maintainer of vst3sdk

**Comment by kant** [comment]
@baconpaul thanks for your swift response!

**Comment by baconpaul** [comment]
No problem. Looks like you are cleaning up our doc in the web editor (thanks!) but that's making a lot of pull requests. Keep doing that of course but when you re done please let me know by tagging one of the issues with some "all done" comment then I will combine them into a single merge for you to keep things clean in master.

Appreciate the work getting things sorted!

**Comment by baconpaul** [comment]
Compressed into #1265

**Pull request closed without merging**
