### PR TITLE
Save the LV2 raw state

### PR DESCRIPTION
**Pull request by jpcima**
#1139

This is raw state saving using data chunks. I tried quickly in Jalv host if it was recognized.
It needs that I test it a bit to check.

### CODE REVIEW

**Comment by jpcima** [comment]
I introduced another LV2 URI as identifier.
It's a possibility to change them prior to release, if they are not satisfying. (they are not significant for functionality, but some dislike using github in URI)

**Comment by baconpaul** [comment]
On the URIs for user exposed URLs we’ve used https://surge-synthesizer.github.io/ rather than github/surge-synt/surge. Don’t know if that’s appropriate here.

Will review this tomorrow at some point. Off for the day now. Thanks for putting it together!

**Comment by baconpaul** [comment]
Oh now I see about the editor. That’s right I added an optional editor state in the recent change to the streaming format.

It’s OK to skip that. We will miss a few things like retaining zoom in the session but I think it’s OK.

I reviewed the rest and it looks correct to me, inasmuch as I understand LV2. I’m happy to merge it. Just let me know what you think about the URI

**Comment by jpcima** [comment]
The choice is yours regarding the URI, they don't have to necessarily be accessible, they are identifiers which are to remain durably for this major version of the synth plugin.

I did a few simple edits.
- I used the website as URL base
- I inserted an imaginary subpath /lv2/
- also I have capitalized `PatchData`. (on second examination of the spec, I think a capital letter is more appropriate for types, whereas a small letter is used for the attributes)

**Comment by baconpaul** [comment]
OK all looks great to me! Merging.

**Pull request merged**
