### PR TITLE
Menu Colors in Skins with a default Dark/Light also

### LINKED ISSUE #5861: Menu tweaks
1. Menus have a light mode (skin based? User pref?  Oth?)
2. The font doesn’t seem to be lato

### PR DESCRIPTION
**Pull request by baconpaul**
New feature in skins menu - menus always dark/light/follow skin
Colors in skin which map to current dark menus by default
Light mode works and sticks

Closes #5861

### CODE REVIEW

**Comment by mkruselj** [comment]
I think I would've preferred per skin colors for the menus rather than a global option, but easy to modify down the road.

**Comment by baconpaul** [comment]
If we had user skin color overrides we could of course get rid of the sticky option

**Comment by mkruselj** [comment]
Is there any way we can get OS light/dark setting then follow it, then just have a single menu option to toggle using menu skin colors from the skin?

**Comment by baconpaul** [comment]
Ha it's funny. I just committed to sstplugin infra saying 'it will all work we just gotta read the registry'

the registry is the api. that's one of the worst things about windows, but it's also true!

**Pull request merged**
