### PR TITLE
LV2 State Restore and Port Consistency

### PR DESCRIPTION
**Pull request by baconpaul**
When we restore the state form XML, we have to set it onto
the ports also, otherwise the value caches won't work.

Addresses #1577

### CODE REVIEW

**Comment by baconpaul** [comment]
@falkTX @jpcima pragmatically, this makes Carla save and load state from the LV2 with no problem at all. Can you review and comment?

I would like to release 1.6.6 on Saturday, and would like to include this diff. Appreciate your looking.

@unfa if you know how to build from a branch in my fork, you can also build this branch and test, but if not that's cool and I will just merge it after review. (or won't and then will release broken still)

Thanks!

**Comment by falkTX** [comment]
Thanks for the patch, but this breaks LV2 spec.
Plugins can only read from ports during run()

**Comment by falkTX** [comment]
Also, plugins are not allowed to change their own input ports.

**Comment by baconpaul** [comment]
Ok
So when I unstream the xml how do I let the ports know they are stale?

**Comment by baconpaul** [comment]
Oh geez your comment is super helpful not o look again. I shouldn’t set the port there I should set the old controller value structure. Ignore my prior question

**Comment by baconpaul** [comment]
Huh yeah ok Carla is restoring port values which are defaulted not which are the saved values - I will close this and write up a clearer report tomorrow

**Pull request closed without merging**
