### PR TITLE
DoubleClick Filter Glyph and WaveShaper Wave to Deactivate

### LINKED ISSUE #5134: Filter bypass action
- [x] Double-click on filter type icon to toggle the filter on/off
- [x] Use existing filter icons, just make them 50% transparent when the filter is off
- [x] Stream that filter state
- [x] ~~Add parameters for host automation~~

### PR DESCRIPTION
**Pull request by baconpaul**
OK fine lets do an inconsistent double click
I mean it *is* faster

Closes #5134

### CODE REVIEW

**Comment by CurlyMC** [comment]
I agree with mkruselj that a double click would be nice and fast way.
But I could also imagine toggling bypass with 1 left click on the icon on the left side of the filters and for the waveshaper 1 left click on the Word 'Waveshaper'... just an idea.

**Comment by CurlyMC** [comment]
... or for the filters just also use the words Filter 1  &   Filter2, as a toggle button ( above the filter balance slider ).

**Comment by baconpaul** [comment]
yeah so i merged the following

1: The menu has an activate/deactivate at the bottom but also
2: double click on the glphy (filter) or wave (waveshaper) deactivates it

and that seems pretty good to me!

**Comment by CurlyMC** [comment]
Thank you Paul,
that sounds good to me.
As a non programmer maybe it's difficult to use the Filter 1, Filter2 and Waveshaper text as a bypass toggle button.
It's up to your experience and programming knowledge !

**Comment by baconpaul** [comment]
Yeah that’s a bit annoying for this point in our cycle and for the small difference in result 

but it’s a great feature! Enjoy it!

**Pull request merged**
