### PR TITLE
 Fine-tuning of low bpm tempo sync overdraws

### PR DESCRIPTION
**Pull request by K0rrid0r**
It's perfect now. Tested in 10 bpm and in 500 bpm. Works flawlessly!

### CODE REVIEW

**Comment by baconpaul** [comment]
Oh man -1.2 is super low. Happy to merge but we do need to remember that it means envelope displays on the SS about .3hz will be wrong. We OK with that? (I am).

**Comment by K0rrid0r** [comment]
can you show me what you mean with a licecap? I cant see the issue.

**Comment by baconpaul** [comment]
Turn an envelope on the step sequencer (dahdsr)
As you adjust the rate the envelope moves correctly
Below rate -1.2 it won’t 
That’s ok

**Comment by baconpaul** [comment]
Anyway merging. We have to choose some threshold right?

**Pull request merged**
