### PR TITLE
build-linux.sh: Do not use the option syntax for commands

### PR DESCRIPTION
**Pull request by jsakkine**
My plan is to parse options with getopt, and differentiate them from
these command, e.g. to select debug/release and the type of plugin.

### CODE REVIEW

**Comment by jsakkine** [comment]
Force-push just to fix typos in the commit message.

**Comment by baconpaul** [comment]
Does this change how you call it? If so does the azure pipeline need an update?

**Comment by jsakkine** [comment]
Does Azure pipeline use it already? If so, yes.

Anyway, I will include this PR to my PR that updates premake5.lua to create makefiles that do code generation for every build. I'll close this one.

**Comment by baconpaul** [comment]
Yup and I see you did too. Cool!

**Comment by baconpaul** [comment]
Just flagging @kzantow so he knows

**Pull request closed without merging**
