### PR TITLE
fix for popup menu scaling on hidpi display

### PR DESCRIPTION
**Pull request by sadguitarius**
Hi all, I've cobbled together a fix for #5811 that hopefully works for other platforms than mine (Windows 10), and also hopefully isn't a trash pile in terms of code quality. This is my first attempt at contributing to the Surge repo, and I'm only somewhat familiar with Juce and its mysteries. I tried to keep variable names and code style more or less in line with what I could find in the Surge code. Please let me know if there's anything that should be done to further clean this up. 

The one issue I'm still running into is that there doesn't seem to be an obvious way to control the scaling of the popup menus within the Lua editor. Does anyone know how to go about this?

Thanks!

### CODE REVIEW

**Comment by baconpaul** [comment]
First, thank you very much for contributing!

I want to give this a whirl on my mac and also review it, but am traveling today. I'll try and make time though among the various activities - perhaps this evening US East Coast time.

I did take a quick skim though. Let me run it on mac but here's a couple of things.

I see you had to thread the editor everywhere. Is that just for the optionsForComponents method? I wonder if the change could be smaller if that was a static in GUIHelpers and also if it automatically generated the point if not included.

That is rather than

```
auto p = cwhere->getLowerLeft()
sge->opstionsForBlah
```

instead do

```
Surge::GUI::MenuOptionsForBlack(chwhere)
```

which internally does

```
auto p = cwhere->getLowerLeft()
// contents of that method
```

also we've generally been using `auto` so `juce::Point<int> x = c->getLower()` is increasingly idiomatic in our code as `auto x = c->getLower()`

**Comment by baconpaul** [comment]
Oh also you should add yourself to the AUTHORS file :)

**Comment by mkruselj** [comment]
Thanks for your contribution, and you're also welcome on our Discord server! 🙂

**Comment by sadguitarius** [comment]
Thanks @baconpaul and @mkruselj! 

I absolutely agree that it's not ideal to have all those pointers to the editor. The reason I did it that way was for the `juce::PopupMenu::Options::withTargetComponent` method, which according to the documentation seems to be the canonical way to get popup menu scaling to behave itself. Since this method needs a reference to an actual instance of a component, I'm guessing it can't be made static as is, but I don't doubt there a better way to get the same thing done. Any ideas?

I do get the point about bringing some of that repeated code into the optionsForPosition methos

**Comment by sadguitarius** [comment]
Thanks @baconpaul and @mkruselj! 

I absolutely agree that it's not ideal to have all those pointers to the editor. The reason I did it that way was for the `juce::PopupMenu::Options::withTargetComponent` method, which according to the documentation seems to be the canonical way to get popup menu scaling to behave itself. Since this method needs a reference to an actual instance of a component, I'm guessing it can't be made static as is, but I don't doubt there a better way to get the same thing done. Any ideas?

I do get the point about bringing some of that repeated code into the `optionsForPosition` method. I think it's pretty much either attaching to the bottom left of another component or using mouse position, so maybe it could be done with just a couple of different method signatures. I'll have to look again at the code, since some of that stuff is a little weird with all the layers of component translations and might need some edge cases. I guess I was trying not to mess with existing methods too much, but if this checks out on Mac as it is now, I'll go in and clean things up a bit more.

Do you think it would be better to pull some of this stuff into a dedicated class?

**Comment by sadguitarius** [comment]
I went ahead and did a little cleanup and it reads much better now. I also found a few menus I'd missed before. One thing-- I can't for the life of me figure out why the oscillator octave popup is showing up either at the top or bottom of the entire window. The same control for the scene octave doesn't do this. What am I missing?

**Comment by baconpaul** [comment]
OK just gave this a whirl

The thing is: this makes the menu appear directly under ever control instead of at the mouse click. I actually think that's an improvement but I'm not sure.

The thing I was worried about (that mac retina zoom would be off) didn't happen.

I can confirm your oscillator switch issue. Let me see if I can debug that.

**Comment by baconpaul** [comment]
Screen Shot 2022-03-18 at 5 53 46 PM

That is, no matter where you click on this selector the menu always positions here.

**Comment by baconpaul** [comment]
@sadguitarius do you mind if I push a diff back to your branch for a potential change to the above location shift?

**Comment by baconpaul** [comment]
[position.patch.txt](https://github.com/surge-synthesizer/surge/files/8307895/position.patch.txt)

Ahh your stuff is on a main ... my git got confused and I can't push to your branch.

Anyway see the above patch file. If you apply this then (1) all your changes are in effect namely everyone gets a component but

(2) the menu positioning is unchanged and the oscillator menu is fixed

If that patch works for you please push again and I'll happily merge and close the issue!

Thanks

**Comment by baconpaul** [comment]
Oh and you are correct this can't be static - needs a ref to the juceEditor indeed!

**Comment by sadguitarius** [comment]
Awesome, just added your diff and all's well. The menu placement thing came about kind of accidentally and I did like it a little, but it was inconsistent when the popup came close to the edge of the screen and Juce moved it around. Any idea about the popup in the Lua editor? I can't see a way to fix its scaling without creating a TextEditor subclass, which seems a bit unnecessary.

**Comment by baconpaul** [comment]
Alas that menu inside the CodeComponent is created by juce with a default popup menu. Short of patching JUCE (or asking juce team for a patch in a future version which I can do once we get this merged) there's no real way to fix it.

I see clang-format is tripping up again; if you can reformat and push when CI finishes I'll merge this and can open a forum issue with juce folks.

Thanks for diving in and fixing this. Anything else in the codebase interest you?

**Comment by sadguitarius** [comment]
Ah, I figured that might be the case. Anyhow, I fixed the formatting so it should be good to go.

I'll take a look at the other issues and see what looks doable. Windows hidpi scaling has been the bane of my existence, so I wanted to tackle that so I can actually use Surge comfortably. I'm very happy to continue contributing the project. Thanks for your help!

**Comment by baconpaul** [comment]
Cool. We also have work to do on shortcircuit, monique, and b-step if any of those are of interest! (And stocks too if you want but that is a bit more stable than SC Mon and Step right now)

**Comment by mkruselj** [comment]
I'm really curious if this menu positioning thing is also going to apply to touch input. I will test it, but it will be really cool if this PR closes #5802 too. 🙂

**Comment by mkruselj** [comment]
Nope, it's actually worse now...

**Comment by baconpaul** [comment]
Yes but the fix is in place
If you look in SGE::popupOptions (or whatever the function is) that takes an argument Component*, bool.
Right now it looks like

```
if !component || !bool
   where = getMouseLocation
else
   where = component->getLowerLeft
```

So modify that to be

```
if !component || !bool
   where = getMouseLocation
else
   where = component->getLowerLeft

if touch
   where = compoent->getLowerLeft

```

and see if that helps

**Comment by baconpaul** [comment]
basically this change is the api fix we need just not the implementation fix

**Comment by mkruselj** [comment]
Ah gotcha! Will give it a shot.

**Pull request merged**
