### PR TITLE
Add the applications and icons to the deb file

### LINKED ISSUE #5846: Shortcuts for Linux
adding the **icons** and **applications** folder (contained in the ZIP file) to `/usr/share` will create shortcuts for Surge XT and Surge XT Effects

it's the same location where the **surge-xt** assets folder resides

image

[SurgeXT-shortcuts.zip](https://github.com/surge-synthesizer/surge/files/7966983/SurgeXT-shortcuts.zip)

ideally this would make it into the deb, rpm and tar.gz as well as be available for packagers of other Linux flavours

### PR DESCRIPTION
**Pull request by baconpaul**
Closes #5846

### CODE REVIEW

**Comment by baconpaul** [comment]
Please hold on merging this. I want to be around to watch the pipeline after we do.

**Comment by mkruselj** [comment]
Those are wrong icons for Surge FX.

**Comment by baconpaul** [comment]
ok i'll deal with this some other time then.

**Comment by mkruselj** [comment]
Oh no need to close the PR, I think I can quickreplace those PNGs tonight!

**Comment by mkruselj** [comment]
@baconpaul Here you go! Just drop and overwrite the "icons" folder.

[icons.zip](https://github.com/surge-synthesizer/surge/files/8203753/icons.zip)

**Comment by baconpaul** [comment]
Thanks! Pushed an update.

**Pull request merged**
