### PR TITLE
Adds stub type definitions to surgepy. Fixes #7362

### LINKED ISSUE #7362: Generate stub files for Python bindings
**Is your feature request related to a problem? Please describe!**
The python build process does not generate stub files, meaning developers using VS Code don't get autocomplete or inline documentation.

**Describe the solution you'd like:**
Running `pybind11-stubgen surgepy` and moving the contents of stubs/surgepy to inside the site-packages surgepy directory results in quite nice inline documentation. This should be added to build process, PR forthcoming.
image

**Describe alternatives you've considered:**
Tried to generate using mypy stubgen but it didn't work.

### PR DESCRIPTION
**Pull request by KingaJanicka**
I've manually ran `pybind11-stubgen surgepy` and added the resulting stubs to the surgepy package install routine. This is similar to how pybind11-stubgen author recommends these stubs be used; see https://github.com/sizmailov/pybind11-stubgen/issues/104#issuecomment-1706128213. 

It's possible there is a better way of accomplishing this, however I am very unfamiliar with skbuild.

### CODE REVIEW

**Comment by narenratan** [comment]
Hi there, Naren here (person who set up the surgepy packaging). This looks great to me! I can successfully pip install surgepy with this branch and the surgepy tests pass.

**Comment by baconpaul** [comment]
You happy to merge 

My only question is what do we do if we update the bindings? Can we add that as a comment in the cpp file so we can keep things in synch?

**Comment by KingaJanicka** [comment]
@baconpaul that sounds like a good idea! I'll leave it to your discretion where to put that. Ideally it would generate the stubs post install but I'm not sure how to do that with skbuild (pybind11-stubgen expects the package to be installed via pip afaik).

**Comment by baconpaul** [comment]
Really just put a block comment in this file after the boilerplate comme t with what you ran
https://github.com/surge-synthesizer/surge/blob/main/src/surge-python/surgepy.cpp

And add yourself to authors and push and we can merge

Cool thanks!

**Comment by KingaJanicka** [comment]
@baconpaul have done both, thank you!

**Comment by baconpaul** [comment]
Awesome one of us can fix up that clang format and merge this for 1.3 this eeek

**Comment by mkruselj** [comment]
@KingaJanicka You haven't added yourself to AUTHORS file. Please do that as well before we merge. :) Thanks!

**Pull request merged**
