### PR TITLE
Rename default macro names for host automation

### PR DESCRIPTION
**Pull request by mkruselj**
From "c0:" to "M1" etc.

### CODE REVIEW

**Comment by baconpaul** [comment]
Oh this will conflict with the accesibility change i just made that did this. I went with "Macro 1" since we have room. I'm gonna close this so I can sweep rest.

**Comment by mkruselj** [comment]
Some hosts will clamp at 16 chars so with some of actually longish macro names it might not fit, but alright!

**Comment by baconpaul** [comment]
Really? I thought VST3 was 64

**Comment by baconpaul** [comment]
But I'll change to M and push mine.

**Comment by mkruselj** [comment]
Ah right yeah VST3 is 64, but VST2 is 16. Heheh. 😅

**Pull request closed without merging**
