### PR TITLE
(XT 1.1) Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S ./libs -L adres,applys,nd,olt,ontext,pard,parm,ro,ser,tbe,te,whichs,wth`

### CODE REVIEW

**Comment by mkruselj** [comment]
@luzpaz We cannot accept this PR unless all affected files are clang formatted. You can see it dials the code quality check.

**Comment by baconpaul** [comment]
Great thanks @luzpaz - we will do a review and merge into our next release.

Is codespell something we could run in our CI pipeline? I see you are a contributor to the project.

**Comment by luzpaz** [comment]
@baconpaul yea, you can make github action to analyze PRs:  
https://github.com/FreeCAD/FreeCAD/blob/master/.github/workflows/codespell.yml
https://github.com/FreeCAD/FreeCAD/blob/master/.github/codespellignore

**Comment by baconpaul** [comment]
Great! We are on azure (we automated our GitHub before actions!) but i'm sure I can figure it out. I'll add an issue.

**Pull request merged**
