### PR TITLE
Remove some unnecessary dynamic vectors/strings

### PR DESCRIPTION
**Pull request by Dave-Lowndes**
Eliminate dynamic vector & string storage where there's a simpler alternative.

Code tweak in prepareForEvaluation to use logical OR rather than bitwise and const the initial bool variable.

### CODE REVIEW

**Comment by baconpaul** [comment]
So this change is in the first half correct but I'm not sure I like it. Naming that white list and table set  makes the code quite a bit clearer i thought.

The second change to a constexpr initializer list is, I think, a c++ 20 thing. At least it doesn't compile in ci with clang for mac.

**Comment by mkruselj** [comment]
That whitelist should've been behind a `// clang-format off` (even if it's a valid clang-format that we use), for further clarity I think.

**Comment by Dave-Lowndes** [comment]
How's this one looking now?

**Comment by baconpaul** [comment]
Great!

**Pull request merged**
