### PR TITLE
Ctrl+click on modbutton arms the unfocused LFO

### PR DESCRIPTION
**Pull request by RaymondBaker**
Implementing the workflow talked about here
https://github.com/surge-synthesizer/surge/issues/5818

It'd be cool if the currently selected lfo had a different colour on the matrix when in this mode but I'm not sure how that would be done.

image
image

### CODE REVIEW

**Comment by mkruselj** [comment]
Please clang-format the modified files, otherwise the PR cannot be merged.

Also, please add yourself to AUTHORS file along with this PR. Thank you for contributing!

**Comment by baconpaul** [comment]
Oh that currently selected skin color is a good idea. If you open a new issue for that I can add a quick hint or two

**Comment by baconpaul** [comment]
And thanks!

**Comment by mkruselj** [comment]
TBH I think we already have way too many colors for modbuttons, so I would be cautious about slapping more.

**Comment by baconpaul** [comment]
And other than the clang format the change looks spot on! Happy to merge once authors and format changes are in. Thank you!

**Pull request merged**
