### PR TITLE
Fix boundFreq method for filter coefficients (#5928)

### PR DESCRIPTION
**Pull request by jatinchowdhury18**
Passing on this fix from sst-filters

### CODE REVIEW

**Comment by baconpaul** [comment]
Does this get the notch filter issue luna reported?

**Comment by jatinchowdhury18** [comment]
Yes! For some reason my PR into the `sst-filters` repo closed that issue automatically.

**Comment by baconpaul** [comment]
Great!

**Comment by mkruselj** [comment]
@jatin Because your commit message mentioned the issue directly. GitHub smartly linked that PR with the issue so that it autocloses when merged. :)

**Pull request merged**
