### PR TITLE
Hardclip bypass

### PR DESCRIPTION
**Pull request by selenologist**
This patch allows the hardclipping before the main volume slider to be disabled by right clicking this slider.

Hard clipping is enabled by default to retain Surge's current behaviour.

Hard clipping state is not saved, the intention is more like giving the user the ability to hear whether their patch was clipping so it can be adjusted.

It also renames this slider to "Main Volume" in line with the renaming of the main branch.

### CODE REVIEW

**Comment by mkruselj** [comment]
I'd kinda want to keep it at Master Volume. We've had this discussion before and IIRC left it as is due to familiarity in audio world. I'd rather back that change out and maybe reopen the discussion on Discord and do a separate PR afterwards.

Also I definitely do think that this switch should be stored in the patch.

**Comment by baconpaul** [comment]
I'm happy to merge this. But I think we should bring #475 into the 180 milestone so I'll do that, and when we do we need to save this param. (@selenologist if you want to do that it would be welcomed!)

as to master vs main two thoughts

1. An irrelevant opinion. I think most audio software will flip this terminology in the next 12 months but hardware labels will of course not. But that doesn't matter because

2. Did you know that with the volume at 0 surge will still make noise! Just put it in dual mode! It is no more the master/main volume than a bus mute is a master/main mute 

So I think the right thing to do is to call this param what it actually is - Scene Volume.

@selenologist if you want to push that tweak I'll merge this and will also bring 475 into this milestone.

**Comment by mkruselj** [comment]
Renaming it to Scene Volume makes sense to me. But then... we REALLY need a proper master volume that governs eeeeeeeverything (and can be a proper mute if need be).

**Comment by mkruselj** [comment]
Oh but WAIT! It's NOT individual scene volume... It does adjust the output of both scenes A and B simultaneously...

**Comment by baconpaul** [comment]
I just tried it in dual mode. And it didn't.
Are you sure that's what you see?

**Comment by mkruselj** [comment]
Positive, both in Reaper, S1, Live and SAVIhost VST3. Acts as master volume for both scenes.

**Comment by baconpaul** [comment]
OK maybe I am using the wrong slider.
Which slider are you using?

**Comment by mkruselj** [comment]
image

**Comment by baconpaul** [comment]
I am using the wrong slider.

**Comment by baconpaul** [comment]
But the scene volume slider works great

**Comment by mkruselj** [comment]
We could rename it to Global Volume I suppose. 

We also have two Output headers so that's confusing as well.

image

**Comment by baconpaul** [comment]
I like Global Volume. Like I said I think this will be a word that the software community moves away from so I'm happy with a change to Main or Global for now.

**Comment by mkruselj** [comment]
Oh, this is also a good chance to provide extend mode for master volume, so that it can go -inf to, say +12?

**Comment by baconpaul** [comment]
Doesn't master volume not stream?

**Comment by baconpaul** [comment]
That's kind of the point of #475

**Comment by mkruselj** [comment]
It's not stored in patch but it is in DAW state.

**Comment by baconpaul** [comment]
Ahh that was clever of me. Then yeah we should definitely add this to the dawExtraState and stream it. Lets do that and change to Global Volume before merge. Sound good @selenologist ?

And thanks!

**Comment by selenologist** [comment]
Sounds good, I'll look at changing the range and saving hardclip state later but for now I've made the label changes from the github web UI - sorry, have to replace a failed drive before I can use my main system. That's why I've been slow to reply too.

**Comment by baconpaul** [comment]
OK cool I'll merge this once CI is done then and then when you are back in action I can show you where how the daw extra streaming code works.

**Comment by mkruselj** [comment]
I think renaming to Scene Volume is not necessary, we should change the title of that section's header to Scene Output instead.

**Pull request merged**
