### PR TITLE
Fixes a rounding issue with host automation not updating the active/deactivated slider state in VST2

### PR DESCRIPTION
**Pull request by K0rrid0r**
Glad to do my first PR.

Fixes a rounding issue with host automation not updating the active/deactivated slider state properly that still existed in VST2 after commit b8f60a51 was merged.

Automating with for example a square waveform or S&H would not update the slider. It is now fixed and I have double checked several times.

How it was

How it is now after this change.

### CODE REVIEW

**Comment by mkruselj** [comment]
Looks fine to me but I'm not sure if changing that condition makes it update UI too often. Paul would know that better.

**Comment by baconpaul** [comment]
Yeah that looks right I just want to check one thing when at my computer

**Comment by baconpaul** [comment]
Oh also toy should add yourself to the authors file and push that on this branch!

**Comment by baconpaul** [comment]
Yeah it used to be sv != cv and when we fixed it we accidentally changed it so the change is good.

We could I suppose check if the state has changed before we do the disablement but the draw is really cheap and only happens on an idle so merging this!

**Pull request merged**
