### PR TITLE
Support builds on alternative c libraries other than glibc for linux

### PR DESCRIPTION
**Pull request by catarial**

### CODE REVIEW

**Comment by baconpaul** [comment]
features.h is not a part of the standard and you included it, breaking all the builds. I think if you remove that and re-push we will see a clean CI.

**Comment by baconpaul** [comment]
Oh my other question. Will __GLIBC__ be defined in, say, a mingw compile? And will that have exec info?

**Comment by catarial** [comment]
> Oh my other question. Will **GLIBC** be defined in, say, a mingw compile? And will that have exec info?

https://stackoverflow.com/questions/6394512/standard-c-library-in-mingw

"MinGW does not build against glibc, it builds against msvcrt. As such, it uses libmsvcrtXX.a instead."

It seems like it doesn't

**Comment by catarial** [comment]
> features.h is not a part of the standard and you included it, breaking all the builds. I think if you remove that and re-push we will see a clean CI.

should I wrap in a `#if LINUX` that header is needed to determine if glibc is being used

**Pull request merged**
