### PR TITLE
some minor tweaks to readme.md

### PR DESCRIPTION
**Pull request by esaruoho**
one more `--` removal

@baconpaul i think i guess this is alright to do?

### CODE REVIEW

**Comment by baconpaul** [comment]
Nope - help actually needs the dashes!

**Comment by esaruoho** [comment]
ok, i'll fix it :D

**Comment by baconpaul** [comment]
But we should fix the script so it also works. Happy to sweep the rest - just lemme know

**Comment by esaruoho** [comment]
> But we should fix the script so it also works. Happy to sweep the rest - just lemme know

well i put it back to `--help`, hope that's fine. it'd be nice if the script was fixed eventually, but overall feels like maybe these tweaks + tiny fixes can be swept in.

**Comment by baconpaul** [comment]
Yeah cool. Thanks!

**Pull request merged**
