### PR TITLE
Consolidate CPU detection to SurgeSynthesizer constructor.

### PR DESCRIPTION
**Pull request by jsakkine**
The only thing that initDllGlobals() does in addition to what
initCpuArchitecture() does, is to print an error message when either SSE2
or CMOV is missing. This commit rips of initDllGlobals() and moves the user
interaction inside initCpuArchitecture().

Signed-off-by: Jarkko Sakkinen <jarkko.sakkinen@iki.fi>

### CODE REVIEW

**Comment by baconpaul** [comment]
So. When I made it so this was consistently called I for a while went this route (called initCpuArchitecture in the plugins rather than initDllGlobals) and then before I did the PR went back to initDllGlobals.

The reason I did that is, for another patch I was working on (which I since abandoned) I also had a function I wanted called cross host at startup reliably. Although as you'll see from the comments I added I hated the name. I think (but am not 100% sure) we will need that call point in the future.

So imagine if we had a second initCpuArchitecture type thing we need to call; or imagine if we had 2 or 3 more host styles (which in standalone modes we would).

So sure lets kill abstract synthesizer but I would really rather have a function called something like Surge::Globals::initialize() which for now only calls initiCpuArchitecture and then reports on the result.

Whether or not we should do user feedback on the architecture state when we set it or outside is a matter of taste. I sort of like it outside - especially if we have a Surge::Globals::initialize

But I consciously choose to not go straight-to-raw and I think that's a choice we will be happy with in the future.

Welcome your thoughts!

**Comment by jsakkine** [comment]
It should be in the SurgeSynthesizers constructor. That is what requires these features. I don't really see why it should be global.

**Comment by jsakkine** [comment]
This is in-between PR going to that direction. After this I'll add similar robustness to other plug-ins (can deal with the init failure). After all that is completed, I'm planning to move the detection code to the synth's constructor. I've written a few lines about this to Slack.

**Comment by jsakkine** [comment]
Cannot be done with a single PR.

**Comment by jsakkine** [comment]
Proposal for getting this PR to .somewhere:

- I will move the CPU detection code to SurgeSynthesizer constructor.
- Not going to throw an exception there, just print the error like initDllGobals does now.

This would not change anything for plugins but things would consolidated where they belong. Once  all plugins have proper exception handling we can make it throw as an exception but right now the UserInteraction would be done in the constructor without exception thrown.

**Comment by jsakkine** [comment]
I will close this now and create a fresh one later.

**Comment by baconpaul** [comment]
All sounds good. Like I said on slack test case is the patches in #181 still work on Mac all hosts. If they do you have it correctly ported. Thanks!!

**Pull request closed without merging**
