### PR TITLE
New features for build-linux.sh

### PR DESCRIPTION
**Pull request by jsakkine**

### CODE REVIEW

**Comment by baconpaul** [comment]
Heya

Happy to merge this but it won't fix 542; we also need to modify the c++ in surge storage to read from usr
 Loca! Share.
can we combine that modification with this script in a single PR?

**Comment by jsakkine** [comment]
Yes. I can do that. I'm also proposing that instead of two commands you would have `--local` for local install as I've integrated getopt already.

**Comment by baconpaul** [comment]
Sounds good to me!

**Comment by jsakkine** [comment]
@baconpaul, can you take this first, fixes-tag has been removed. Decided to take some time to do all requested features to script, like selecting a specific target and the debug build. Now have take a break and do the code change later.

**Comment by baconpaul** [comment]
Yeah no problem. Let me just read it. We can do the code change in a separate PR. 

Looking now.

**Comment by baconpaul** [comment]
Looks great to me.
I'm about to take off. Why don't you just merge this once the automatic builds report success?
Thanks!

**Comment by jsakkine** [comment]
Another push (just updated the help text, that's all).

**Pull request merged**
