### PR TITLE
Save various editor states in DAW state

### PR DESCRIPTION
**Pull request by mkruselj**
* Currently selected FX slot
* Currently selected modbutton
* Per scene selected modsource editor

### CODE REVIEW

**Comment by mkruselj** [comment]
Addresses #2791!

**Comment by baconpaul** [comment]
Unclear what’s left to do here. @mkruselj i think we are all done with your merge above yeah? Should we close this?

**Comment by mkruselj** [comment]
@baconpaul Would be nice if MSEG editor open state survived destroy/recreate.

**Comment by baconpaul** [comment]
Gotcha - totally doable

**Pull request merged**
