### PR TITLE
[WIP] ARM NEON intrinsics

### PR DESCRIPTION
**Pull request by jsakkine**
Closes:  #570

### CODE REVIEW

**Comment by baconpaul** [comment]
Wow that works? That is really powerful!
(do we need a LICENSE.txt in libs/sseblah btw? That's one thing I would ask).
Great stuff!

**Comment by jsakkine** [comment]
@baconpaul, should work. It is used at least in this project: https://github.com/f4exb/cm256cc. I want to test compilation before merging.

**Comment by baconpaul** [comment]
How cool!

If you could take a peek also at my steinberg pull request resolution - it's a 10 minute read - and make sure you don't hate the way I had to integrate windows UTF8 too much I'd appreciate it.

It is obviously not ideal but I don't see an easy other route.

**Comment by esaruoho** [comment]
should i test this with raspberry pi? or how much of this is still in WIP?

**Comment by jsakkine** [comment]
Well, if you know how to compile and run it yourself without support. It is dependent on BuildRoot packaging, which is dependent on building headless with CMake, which is dependent on getting Windows headless done with CMake, which I postponed until I have PR ready for Linux user interactions because it has higher priority.

**Comment by esaruoho** [comment]
what's going on with this pr?

**Comment by jsakkine** [comment]
should have soon time to start working on surge again. not much extra time have had lately.

**Comment by baconpaul** [comment]
Cool. I'm about to make the ARM port much easier for you also ... just decoupled headless from both vst3sdk and vstgui completely. PR and sweep coming.

**Comment by jsakkine** [comment]
Windows headless works already, doesn't it? I guess what was missing from Windows is that it does not build with CMake? Just recapping.

**Comment by baconpaul** [comment]
Yeah just uses premake still.

But I modified mac and linux headless to have no reference to VST3SDK or VSTGUI which should make headless ports easier. (And will make the VCV Rack port easier which is why I did it!)

**Comment by jsakkine** [comment]
@baconpaul, answer to your earlier question: we don't need a separate LICENSE.txt because the header itself contains the license plate. It is licensed with MIT, which are compatible with.

**Comment by baconpaul** [comment]
Heya seems like this PR isn't rebased against master properly - it has the windows commit in it also. Can you clean that up and I'll take a look? Thanks!

**Comment by jsakkine** [comment]
still wip

**Comment by baconpaul** [comment]
Oh sorry I saw the force push and the review request! Lemme know when it’s ready. Exciting stuff!

**Pull request closed without merging**
