### PR TITLE
Upgrade to SIMDe v0.7.0

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by baconpaul** [comment]
Hi!

Thanks for doing this. 

We are really close to our 1.8 release and we don't have M1 testing hardware. Volunteers tested our nightly with the prior SIMDE lib on M1, but I might wait to merge this until after our release unless

1. It fixes known SSE2 path bugs (seems most of the diffs are > SSE2 and we don't use those APIs) or
2. Do you happen to ahve any Apple Silicon hardware around to do a quick test for us?

Thank you!

**Comment by mr-c** [comment]
Hey @baconpaul !

If it worked before, then there is no urgency. I don't have an M1 to test with.

But this update does have a lot of improved NEON optimizations of the SSE/SSE2 intrinsics used in surge :-)

[sse,sse2: added NEON implementation of mm_rsqrt_ss,mm_sll_epi{16,32,64} ](https://github.com/simd-everywhere/simde/commit/1e9a647abd3aba114458de6e8eb30e007179b4fc) 
```
$ git grep mm_rsqrt_ss
src/common/dsp/DspUtilities.cpp:   __m128 m1 = _mm_rsqrt_ss(_mm_load_ss(&m));
src/common/dsp/DspUtilities.cpp:   __m128 m1 = _mm_rsqrt_ss(_mm_load_ss(&m));
```

[sse2: add NEON implementations of simde_mm_cvtps_p{s,d}](https://github.com/simd-everywhere/simde/commit/63905323f86be5c9b99fc9608a594f9e4eb0cd02)
```
$ git grep _mm_cvtps_p
src/common/dsp/BiquadFilterSSE2.cpp:            __m128d input = _mm_cvtps_pd(v0);
src/common/dsp/BiquadFilterSSE2.cpp:            input = _mm_cvtps_pd(v0);
src/common/dsp/BiquadFilterSSE2.cpp:            input = _mm_cvtps_pd(v0);               
src/common/dsp/BiquadFilterSSE2.cpp:            input = _mm_cvtps_pd(v0);               
src/common/dsp/BiquadFilterSSE2.cpp:            __m128d input = _mm_cvtps_pd(v0);
src/common/dsp/BiquadFilterSSE2.cpp:            input = _mm_cvtps_pd(v0);               
src/common/dsp/BiquadFilterSSE2.cpp:            input = _mm_cvtps_pd(v0);                               
src/common/dsp/BiquadFilterSSE2.cpp:            input = _mm_cvtps_pd(v0);                               
src/common/dsp/BiquadFilterSSE2.cpp:            __m128d input = _mm_cvtps_pd(v0);
src/common/dsp/BiquadFilterSSE2.cpp:            input = _mm_cvtps_pd(v0);
src/common/dsp/BiquadFilterSSE2.cpp:            input = _mm_cvtps_pd(v0);               
src/common/dsp/BiquadFilterSSE2.cpp:            input = _mm_cvtps_pd(v0);
```

[sse2: add NEON implementation of simde_mm_cvtss_sd ](https://github.com/simd-everywhere/simde/commit/66b3f35eeef548a287bb3932c6f2724f1fd9c34f)
```
$ git grep _mm_cvtss_sd
src/common/dsp/BiquadFilterSSE2.cpp:            __m128d input = _mm_cvtss_sd (input, vl);
src/common/dsp/BiquadFilterSSE2.cpp:            input = _mm_cvtss_sd (input, _mm_shuffle_ps(vl,vl,_MM_SHUFFLE(0, 0, 0, 1)));
src/common/dsp/BiquadFilterSSE2.cpp:            input = _mm_cvtss_sd (input, _mm_shuffle_ps(vl,vl,_MM_SHUFFLE(0, 0, 0, 2)));
src/common/dsp/BiquadFilterSSE2.cpp:            input = _mm_cvtss_sd (input, _mm_shuffle_ps(vl,vl,_MM_SHUFFLE(0, 0, 0, 3)));
```
[_mm_sub_pd NEON implementation](https://github.com/simd-everywhere/simde/commit/96e2bc1f2859b1d6f9f2875e44424578d9f94149)

[sse2: add NEON implementations of simde_mm_set{,1}_pd ](https://github.com/simd-everywhere/simde/commit/ae72884ae4871b4fdd979a459960aa6dbe66d343)
```
$ git grep _mm_set1_pd
src/common/dsp/BiquadFilter.h:const __m128d vl_lpinv = _mm_set1_pd(1.0 - 0.004);*/
```
[_mm_unpack{hi,lo}_pd NEON implementation](https://github.com/simd-everywhere/simde/commit/d3f202791b2c0dcf875496663432b14760026a89)
```
$ git grep _mm_unpacklo_pd
src/common/dsp/BiquadFilter.h:           v.v = _mm_unpacklo_pd(v.v,v.v);
src/common/dsp/BiquadFilterSSE2.cpp:            __m128 sl = _mm_cvtpd_ps(_mm_unpacklo_pd(op0,op1)); 
src/common/dsp/BiquadFilterSSE2.cpp:            sl = _mm_movelh_ps(sl,_mm_cvtpd_ps(_mm_unpacklo_pd(op2,op3))); 
src/common/dsp/BiquadFilterSSE2.cpp:            __m128 sl = _mm_cvtpd_ps(_mm_unpacklo_pd(op0,op1)); 
src/common/dsp/BiquadFilterSSE2.cpp:            sl = _mm_movelh_ps(sl,_mm_cvtpd_ps(_mm_unpacklo_pd(op2,op3))); 
src/common/dsp/BiquadFilterSSE2.cpp:            __m128 sl = _mm_cvtpd_ps(_mm_unpacklo_pd(op0,op1)); 
src/common/dsp/BiquadFilterSSE2.cpp:            sl = _mm_movelh_ps(sl,_mm_cvtpd_ps(_mm_unpacklo_pd(op2,op3))); 
src/common/dsp/BiquadFilterSSE2.cpp:            __m128 sl = _mm_cvtpd_ps(_mm_unpacklo_pd(op0,op1)); 
src/common/dsp/BiquadFilterSSE2.cpp:            sl = _mm_movelh_ps(sl,_mm_cvtpd_ps(_mm_unpacklo_pd(op2,op3))); 
```

[Improve NEON implementation of _mm_store_sd](https://github.com/simd-everywhere/simde/commit/a9e83540d324b0d594d1c6bc3cbd9793eb5f0474)
```
$ git grep _mm_store_sd
src/common/dsp/BiquadFilterSSE2.cpp:            _mm_store_sd(data+k,op0);
src/common/dsp/BiquadFilterSSE2.cpp:            _mm_store_sd(data+k,op0);
src/common/vt_dsp/basic_dsp.cpp:   _mm_store_sd(&a, _mm_max_sd(_mm_load_sd(&a), _mm_load_sd(&b)));
```

[sse2: improve simde_mm_madd_epi16 NEON & AltiVec implementations ](https://github.com/simd-everywhere/simde/commit/55f703f9b48f539c543a356eb91eef83b826e590)
```
$ git grep _mm_madd_epi16
src/common/dsp/WindowOscillator.cpp:            __m128i Wave = _mm_madd_epi16(_mm_load_si128(((__m128i*)sinctableI16 + MSPos)), _mm_loadu_si128((__m128i*)&WaveAdr[MPos]));
src/common/dsp/WindowOscillator.cpp:            __m128i Win = _mm_madd_epi16(_mm_load_si128(((__m128i*)sinctableI16 + WinSPos)), _mm_loadu_si128((__m128i*)&WinAdr[WinPos]));
```
[sse2: added NEON impl for mm_shuffle_epi32,mm_shuffle{lo,hi}_epi16](https://github.com/simd-everywhere/simde/commit/8525eba2bf37e3784cfbc4188295ae036bf409a4)
```
$ git grep _shuffle_epi32
src/common/dsp/WindowOscillator.cpp:            iWin[1] = _mm_cvtsi128_si32(_mm_shuffle_epi32(Win, _MM_SHUFFLE(1, 1, 1, 1)));
src/common/dsp/WindowOscillator.cpp:            iWin[2] = _mm_cvtsi128_si32(_mm_shuffle_epi32(Win, _MM_SHUFFLE(2, 2, 2, 2)));
src/common/dsp/WindowOscillator.cpp:            iWin[3] = _mm_cvtsi128_si32(_mm_shuffle_epi32(Win, _MM_SHUFFLE(3, 3, 3, 3)));
src/common/dsp/WindowOscillator.cpp:            iWave[1] = _mm_cvtsi128_si32(_mm_shuffle_epi32(Wave, _MM_SHUFFLE(1, 1, 1, 1)));
src/common/dsp/WindowOscillator.cpp:            iWave[2] = _mm_cvtsi128_si32(_mm_shuffle_epi32(Wave, _MM_SHUFFLE(2, 2, 2, 2)));
src/common/dsp/WindowOscillator.cpp:            iWave[3] = _mm_cvtsi128_si32(_mm_shuffle_epi32(Wave, _MM_SHUFFLE(3, 3, 3, 3)));
$ git grep mm_shufflelo_epi16
src/common/dsp/QuadFilterUnit.cpp:   e4[1] = _mm_cvtsi128_si32(_mm_shufflelo_epi16(e, _MM_SHUFFLE(1, 1, 1, 1)));
src/common/dsp/QuadFilterUnit.cpp:   e4[2] = _mm_cvtsi128_si32(_mm_shufflelo_epi16(e, _MM_SHUFFLE(2, 2, 2, 2)));
src/common/dsp/QuadFilterUnit.cpp:   e4[3] = _mm_cvtsi128_si32(_mm_shufflelo_epi16(e, _MM_SHUFFLE(3, 3, 3, 3)));
src/common/dsp/QuadFilterUnit.cpp:   e4[1] = _mm_cvtsi128_si32(_mm_shufflelo_epi16(e, _MM_SHUFFLE(1, 1, 1, 1)));
src/common/dsp/QuadFilterUnit.cpp:   e4[2] = _mm_cvtsi128_si32(_mm_shufflelo_epi16(e, _MM_SHUFFLE(2, 2, 2, 2)));
src/common/dsp/QuadFilterUnit.cpp:   e4[3] = _mm_cvtsi128_si32(_mm_shufflelo_epi16(e, _MM_SHUFFLE(3, 3, 3, 3)));
```
[sse: added NEON impl for mm_shuffle_ps](https://github.com/simd-everywhere/simde/commit/17772242b4eb5b5b7ce920f861f41370b4f62476)
```
$ git grep -l mm_shuffle_ps
src/common/dsp/BiquadFilterSSE2.cpp
src/common/dsp/SampleAndHoldOscillator.cpp
src/common/dsp/SurgeSuperOscillator.cpp
src/common/dsp/WavetableOscillator.cpp
src/common/dsp/effect/Reverb1Effect.cpp
src/common/vt_dsp/basic_dsp.h
src/common/vt_dsp/halfratefilter.cpp
src/common/vt_dsp/lipol.h
src/common/vt_dsp/portable_intrinsics.h
src/todo/sub3_osc_wavetable2.cpp
```
---

Fixes 

[sse: fix NaN handling for _mm_max_ps](https://github.com/simd-everywhere/simde/commit/15aa0c493a29cb6e95a302b91dae61eefb40d923)
[sse, sse2, sse4.1: fix ties-toward-even rounding](https://github.com/simd-everywhere/simde/commit/3208aeb368de8aaf3d7d2b695ad98d35138762b9)

**Comment by baconpaul** [comment]
Huh wow yeah those are API points we use a lot. And I know you have a squllion regtests right?

Maybe I should just merge then. I can fire up my PI and give it a whirl too. Or maybe I'll just bike down to the apple store and pick up a mini 👍 

Will ponder! Thank you.

**Comment by baconpaul** [comment]
OK I fired up the RPI and ran our retests on native ARM64.

```
pi@raspberrypi:~/surge $ SURGE_DISABLE_NETWORK_TESTS=TRUE ./build/surge-headless 
# surge-headless: 1.8.simde_v0.7.0.8aa48e2b built: 2021-01-01 15:25:46
===============================================================================
All tests passed (3810914 assertions in 52 test cases)
```

so I'm going to merge this! Will try and re-confirm M1 but reviewing the changes, and that it builds properly, I am confident in the upgrade.

Thank you.

**Comment by mr-c** [comment]
Glad to hear it @baconpaul ; enjoy!

**Comment by baconpaul** [comment]
And thanks for providing the library. It is truly a life saver for us

**Pull request merged**
