### PR TITLE
docs: update references to Arch Linux port

### PR DESCRIPTION
**Pull request by grawlinson**
Hello! :wave:

Package maintainer for Arch Linux here, I've just added `surge-xt` to our repositories.

Hopefully this change to documentation is acceptable, let me know if it requires any further changes.

### CODE REVIEW

**Comment by mkruselj** [comment]
@grawlinson Thanks for the PR!

One thing I would perhaps add is link to the list of maintainers (if there is one), and definitely a direct link for the bug report issue template on your github?

**Comment by haenkel** [comment]
Adding this link would be sufficient:
https://archlinux.org/packages/community/x86_64/surge-xt/

**Comment by baconpaul** [comment]
Oh surge builds fine on arm64 also - just noticed the build instruction is x86 64. But I don’t understand arch so this comment may be useless

**Comment by baconpaul** [comment]
Thanks so much!

**Pull request merged**
